Data preprocessing

In [3]:
import pandas as pd
import numpy as np

In [4]:
s1 = pd.read_csv('train_source1.tsv',sep='\t')

In [5]:
s2 = pd.read_csv('train_source2.tsv',sep='\t')

In [6]:
s3 = pd.read_csv('train_source3.tsv',sep='\t')

In [7]:
truth = pd.read_csv('train_ground_truth.tsv',sep='\t')

In [8]:
print("S1:", s1.shape)
print("S2:", s2.shape)
print("S3:", s3.shape)
print("Truth:", truth.shape)

print(s1.head())
print(s2.head())
print(s3.head())
print(truth.head())

S1: (2206821, 4)
S2: (5034616, 4)
S3: (5285603, 4)
Truth: (2206821, 2)
      entity_id            business_name  \
0  S1-925783039      Orelee's Barbershop
1  S1-773889195              Prime Money
2  S1-377745466            B+ Retail Inc
3  S1-133037285            Christ Chapel
4  S1-755362802  Prabhav Business Center

                                    business_address country
0             1795 Westchester Drive, High Point, NC      US
1                    17560 Ellis Road, Tahlequah, OK      US
2                1712 Montebello Avenue, Phoenix, AZ      US
3  2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD      US
4  797, Lake Town Block A, Kolkata, Howrah, West ...   India
      entity_id                    business_name  \
0  S2-166376419  राम मार्केटिंग प्राइवेट लिमिटेड
1  S2-764573417     -- Holloway Peak Inc Seafood
2  S2-639257739         आदित्य प्रॉपर्टीज एलएलपी
3  S2-163963287                       Summit Inc
4   S2-49942811     Delta Tetlecommunication Inc

                                   business_address country
0      KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi   India
1                         105 ELM ST, MORGANTON, NC      US
2  G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh   India
3             GREENSBORO, NC, 19 1/2 STARDUST TRAIL      US
4                   914 PIERPONT AVE, CLEVELAND, OH      US
      entity_id                                business_name  \
0  S3-202863386                           wilfordhancock.com
1  S3-859268022  International South Consultants Private Ltd
2   S3-22467283                  LLC Moncada Léarning Center
3  S3-671162755                               Moyna's Coffee
4  S3-960981775                 Pvt. EFS Print Ventures Ltd.

                                    business_address country
0                        Mack Rd, Haltom City, Texas      US
1                                                NaN   India
2                    5780 Fawn Ct, Fort Worth, Texas      US
3       1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio      US
4  Door No 183, 41St Cross, 22Nd Main 9Th Block J...   India
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [9]:
print(s1.columns)
print(s2.columns)
print(s3.columns)
print(truth.columns)

Index(['entity_id', 'business_name', 'business_address', 'country'], dtype='object')
Index(['entity_id', 'business_name', 'business_address', 'country'], dtype='object')
Index(['entity_id', 'business_name', 'business_address', 'country'], dtype='object')
Index(['source1_entity_id', 'matched_entity_ids'], dtype='object')

In [10]:
pd.set_option('display.max_colwidth',200)

print(
    s1[["entity_id", "business_name", "country"]].head(30).to_string(index=False)
)

   entity_id                            business_name country
S1-925783039                      Orelee's Barbershop      US
S1-773889195                              Prime Money      US
S1-377745466                            B+ Retail Inc      US
S1-133037285                            Christ Chapel      US
S1-755362802                  Prabhav Business Center   India
S1-851869949               Custom Wealth Services LLC      US
S1-785847572 Consulting Nyasa Nursing Private Limited   India
 S1-27541239                        Nexus Anchor Rain      US
S1-629417405                        Moore Bitwise Inc      US
 S1-22305073               Dermatology Green Medicine      US
S1-504790211                       Crystal Lending PC      US
S1-564729135               Dream Construction Limited   India
S1-236312382                      Kelly Advisory, Inc      US
S1-865131206                                   Helios      US
S1-626914593                   Unified Choice Dynamix      US
S1-765734254               Health Fellowship Partners      US
 S1-82053739         Smart Healthcare Private Limited   India
S1-309349399                   Callicoat & Dailey Inc      US
S1-221443075                            Iris Advisors   India
S1-341506266        Secunderabad Park Private Limited   India
S1-990319941                           Holy Synagogue      US
S1-597762257          Green Logistics Private Limited   India
S1-661315962                          Scott Eagle Inc      US
S1-716574008             Rajani Enterprises of Kannur   India
S1-985038901  Schaefer, Michael and Silver Associates      US
S1-404435514                  Colline Molitor Sea LLC      US
S1-252242682                 Aggie E. Nagle, L.C.S.W.      US
S1-981440385                     Angad Multitrade Ltd   India
S1-883973644                     Global Hovnanian LLC      US
 S1-17666546        Pacific Learning Laboratories LLC      US

In [11]:
print(
    s2[["entity_id", "business_name", "country"]].head(30).to_string(index=False)
)

   entity_id                                                            business_name country
S2-166376419                                          राम मार्केटिंग प्राइवेट लिमिटेड   India
S2-764573417                                             -- Holloway Peak Inc Seafood      US
S2-639257739                                                 आदित्य प्रॉपर्टीज एलएलपी   India
S2-163963287                                                               Summit Inc      US
 S2-49942811                                             Delta Tetlecommunication Inc      US
S2-138046867                                                           Lee and Lawson      US
S2-584977605 SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPORATION | www.shivshakti.com   India
S2-277444929                                               Shree Infracon Private Ltd   India
S2-721031885                                             Chavira Platinum Chimera LLC      US
S2-508602797                                 FOUNDATION EXCEL AGENCY PRIVATE  LIMITED   India
 S2-69394310                                                         heassociates.com      US
S2-615967906                                         सन कंस्ट्रक्शंस प्राइवेट लिमिटेड   India
S2-684635925                               Global Developers Medicals Private Limited   India
S2-868087865                                             ASSET BUILDING COALITION LLC      US
S2-795141272                                        Olszewski Holding Company LLC LLC      US
S2-414418413                                                         CANDY'S-SERVICES      US
S2-566688803                                                  रियल मॉडर्न फूड लिमिटेड   India
S2-634015823                                             Crestline Crestline Clean LP      US
S2-378707035                                                                     Nion      US
S2-953098128                                             Keystone Odyssey Odyssey LLC      US
S2-526991413                                                  Jones Royal  Bancshares      US
S2-879667609                                        குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்   India
S2-202057528                                                          Altitude Retail   India
S2-763108962                                                 Core Welfare Society LLP   India
S2-415733261                                                    Sweet Barbershop (Co)      US
S2-294835210                                                            COBALT  (LLC)      US
S2-944853638                                          Piedmont Complete Chile  L.L.C.      US
S2-235039028                                                Empire School of Medicine      US
S2-783158461                                                   Animal Welfare Nétwork      US
S2-669879950                                               Hail, Harris & Roberts Inc      US

In [12]:
print(
    s3[["entity_id", "business_name", "country"]].head(30).to_string(index=False)
)

   entity_id                               business_name country
S3-202863386                          wilfordhancock.com      US
S3-859268022 International South Consultants Private Ltd   India
 S3-22467283                 LLC Moncada Léarning Center      US
S3-671162755                              Moyna's Coffee      US
S3-960981775                Pvt. EFS Print Ventures Ltd.   India
S3-578159284              LLC Hernandez Colonial Redwood      US
S3-121412624               Classic Equity Partners Group      US
S3-249416830              Ectolumdrex dba X+ Madison Inc      US
S3-107644605                     Animal Hanisch Hospirlg      US
S3-160217003                               Gomez Optimal      US
S3-504183980            The Rapid  Learning Alliance LLC      US
 S3-53737228                  Indian Care Public Limited   India
 S3-16693061                                       Béque      US
S3-331103166                           #centraleducation      US
 S3-45067784         அரிஹந்த் Foundation Private Limited   India
S3-118652570                         Wildlife Guild  LLC      US
 S3-90100170                          Cinder Charlton-PC      US
S3-476778426                              ZRO Trinity Co      US
S3-128062172           Bajaj Foundation  Private Limited   India
S3-171901473                           Estell's Creative      US
S3-973629095                          Center 5uperior Co      US
S3-554084947                            Palace Vidyalaya   India
S3-315861895                              Global Applied      US
S3-326049086                Integrated  Business Systems      US
S3-181819854 Cardiology Heartland Cáre Associates #98825      US
S3-776815069                   Sai  Surgical (India) Ltd   India
S3-230314480 MW Management Private  Limited - 2067865001   India
S3-807500071                        FERRERO FERRERO DUKE      US
S3-878295053           Chinglepet Private Limited Center   India
S3-725749046                      Modern Center Brothers   India

In [13]:
print(truth.head(20).to_string(index=False))

source1_entity_id                                                                        matched_entity_ids
        S1-965667                           S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
      S1-55344266                                       S2-249013014,S2-197070651,S3-478195123,S3-384364074
     S1-343815751                                                    S2-790675320,S2-479876582,S3-878454467
     S1-656753428                                                     S2-153058913,S2-24659151,S3-679606215
     S1-102811957             S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785
      S1-18727616                                       S2-755677256,S3-187831601,S3-641489370,S3-476250621
     S1-318373630                                                                 S2-660036492,S3-804600254
      S1-86989137                                                                 S3-274817120,S3-312496301
      S1-29845983                                                                 S2-648035184,S3-588502663
     S1-789009573                                                     S2-383871912,S3-74481402,S3-576451439
     S1-730934468                                                                 S2-356983532,S3-352439310
       S1-7293388                                         S2-7028416,S2-442723188,S2-157073701,S3-523120965
     S1-546142636             S2-487600131,S2-582477216,S2-392804085,S3-200008747,S3-729771680,S3-249331830
     S1-274126313              S2-736616474,S2-680265918,S2-51486805,S3-925631694,S3-461175723,S3-850112871
     S1-145361722                                                     S2-120366543,S2-939389287,S3-96572514
     S1-503957000 S2-994658326,S2-235117490,S2-353308450,S2-173295926,S3-858763214,S3-33665521,S3-555791452
     S1-692000596                                                                 S2-580419223,S3-164220452
     S1-561341312                                                                 S2-483615364,S3-619529814
     S1-777597828                                                                 S2-836452886,S3-413669121
     S1-282467635                                                                 S2-938895481,S3-138350041

In [14]:
s1_lookup = s1.set_index('entity_id')
s2_lookup = s2.set_index('entity_id')
s3_lookup = s3.set_index('entity_id')


def show_matches(s1_id):

    print('=' * 100)

    s1_row = s1_lookup.loc[s1_id]

    # S1 record
    print("S1")
    print("ID      :", s1_id)
    print("NAME    :", s1_row["business_name"])
    print("ADDRESS :", s1_row["business_address"])
    print("COUNTRY :", s1_row["country"])

    # Ground truth
    truth_row = truth[truth["source1_entity_id"] == s1_id]

    matched_ids = truth_row.iloc[0]["matched_entity_ids"].split(",")

    print("\nTRUE MATCHES:")

    for entity_id in matched_ids:

        entity_id = entity_id.strip()

        if entity_id.startswith("S2-"):
            row = s2_lookup.loc[entity_id]

        elif entity_id.startswith("S3-"):
            row = s3_lookup.loc[entity_id]

        print("\n", entity_id)
        print("NAME    :", row["business_name"])
        print("ADDRESS :", row["business_address"])
        print("COUNTRY :", row["country"])

In [15]:
show_matches("S1-55344266")

====================================================================================================
S1
ID      : S1-55344266
NAME    : Raj Investments LLP
ADDRESS : 6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu
COUNTRY : India

TRUE MATCHES:

 S2-249013014
NAME    : ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி
ADDRESS : 6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, CHENNAI, Tamil Nadu
COUNTRY : India

 S2-197070651
NAME    : Raj Investments LLP
ADDRESS : 6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, CHENNAI, Tamil Nadu
COUNTRY : India

 S3-478195123
NAME    : Raj Investments எல்எல்பி
ADDRESS : 6(29), C.i.t. Colony, 2Nd Main Road Mylapore, Chennai, TN
COUNTRY : India

 S3-384364074
NAME    : ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி
ADDRESS : 6(29), C.i.t. Colony, 2Nd Main Road Mylapore, Chennai, தமிழ்நாடு
COUNTRY : India

In [16]:
sample_truth = truth.sample(1000, random_state=42)

In [17]:
## creating true pairs
pairs = []

for _, row in sample_truth.iterrows():

    s1_id = row["source1_entity_id"]
    matched_ids = str(row["matched_entity_ids"]).split(",")

    s1_row = s1_lookup.loc[s1_id]

    for entity_id in matched_ids:

        entity_id = entity_id.strip()

        if entity_id.startswith("S2-"):
            matched_row = s2_lookup.loc[entity_id]

        elif entity_id.startswith("S3-"):
            matched_row = s3_lookup.loc[entity_id]

        else:
            continue

        pairs.append({
            "s1_name": s1_row["business_name"],
            "matched_name": matched_row["business_name"],
            "s1_address": s1_row["business_address"],
            "matched_address": matched_row["business_address"],
        })

sample_pairs = pd.DataFrame(pairs)

In [18]:
sample_pairs.head(20)

,s1_name,matched_name,s1_address,matched_address
0,"FQ Social, Inc","FQ Social, Inc.","1212 Old Rte 34, Sandwich, IL","1212 OLD RTE 34, SANDWICH, IL"
1,"FQ Social, Inc","FQ Social, #42836","1212 Old Rte 34, Sandwich, IL","1212 OLD RTE 34, SANDWICH, IL"
2,"FQ Social, Inc","FQ Social, Ínc","1212 Old Rte 34, Sandwich, IL","1212 Old Rte 34, Sandwich, Illinois"
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc","1212 Old Rte 34, Sandwich, IL","1212 Old Rte 34, Sandwich, IL"
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,"15 16 Indrapuri Madhubancolony Karvenagar, Pune, Maharashtra","H.NO B3/15 16 INDRAPURI MADHUBANCOLONY KARVENAGAR, PUNE, POONA, महाराष्ट्र"
5,Innovative Consultants,Innovative Consultants,"15 16 Indrapuri Madhubancolony Karvenagar, Pune, Maharashtra",NaN
6,Innovative Consultants,Innovative Consultants,"15 16 Indrapuri Madhubancolony Karvenagar, Pune, Maharashtra","#B3/15 16 INDRAPURI MADHUBANCOLONY KARVENAGAR, PUNE, Maharashtra"
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,"9-14, Hari Krishna Building, 2Nd Fl Dilsukhnagar, Hyderabad, Telangana","G-9-14, HARI KRISHNA BUILDING, 2ND FL DILSUKHNAGAR, HYDERABAD, తెలంగాణ"
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,"9-14, Hari Krishna Building, 2Nd Fl Dilsukhnagar, Hyderabad, Telangana","9-14, Hari Krishna Building, 2Nd Fl Dilsukhnagar, Hyderabad, Andhra Pradesh"
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]","Hampton City, VA, 234 Summit Court","SUMMIT CT, HAAMPTON, VA"
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc","Hampton City, VA, 234 Summit Court","234-236 SUMMIT COURT, HAAMPTON, VA"
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods","Hampton City, VA, 234 Summit Court","34 Summit Ct, Hampton, Virginia"
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,"4484 Westwood Drive, West Des Moines, IA","IA, WEST DES MOINES, 4484D WESTWOOD DRIVE"
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,"4484 Westwood Drive, West Des Moines, IA","4484- Westwood Drive, West Des Moines, Iowa"
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center","4484 Westwood Drive, West Des Moines, IA","4484- Westwood Dr, West Des Moines, Iowa"
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,"Vill-Belpukur, P.O. Balarampur, Berhampore, Murshidabad, West Bengal","West Bengal, VILL-BELPUKUR, P.O. BALARAMPUR, BERHAMPORE, MURSHIDABAD"
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,"Vill-Belpukur, P.O. Balarampur, Berhampore, Murshidabad, West Bengal","West Bengal, VILL-BELPUKUR, P.O. BALARAMPUR, BERHAMPORE, MURSHIDABAD"
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,"Vill-Belpukur, P.O. Balarampur, Berhampore, Murshidabad, West Bengal","VILL-BELPUKUR, P.O. BALAMAMPUR, BERHAMPORE, MURSHIDABAD, West Bengal"
18,Reet Exports (India) Private Limited,reetexportsindia.com,"Vill-Belpukur, P.O. Balarampur, Berhampore, Murshidabad, West Bengal","VILL-BELPUKUR, P.O. BALARAMPUR, BERHAMPORE, MURSHIDABAD, West Bengal"
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,"Vill-Belpukur, P.O. Balarampur, Berhampore, Murshidabad, West Bengal","Vill-belpukur, Murshidabad, WB"

In [19]:
print(sample_pairs.shape)

(3559, 4)

In [20]:
## robust normalization(robust normalized name + core name)
import re
import unicodedata

def normalize_name(name):
    if pd.isna(name):
        return ""

    name = str(name).lower()

    # Normalize accented characters
    name = unicodedata.normalize("NFKD", name)
    name = "".join(
        ch for ch in name
        if not unicodedata.combining(ch)
    )

    # Remove URLs
    name = re.sub(r"https?://\S+|www\.\S+", " ", name)

    # Replace punctuation with spaces
    name = re.sub(r"[^a-z0-9\s]", " ", name)

    # Remove extra spaces
    name = re.sub(r"\s+", " ", name).strip()

    return name

In [21]:
test_names = [
    "FQ Social, Inc",
    "FQ Social, Inc.",
    "FQ Social, Ínc",
    "Arcxylo DBA FQ Social, Inc"
]

for name in test_names:
    print(name, " -> ", normalize_name(name))

FQ Social, Inc  ->  fq social inc
FQ Social, Inc.  ->  fq social inc
FQ Social, Ínc  ->  fq social inc
Arcxylo DBA FQ Social, Inc  ->  arcxylo dba fq social inc

In [22]:
## extracting suffixes
SUFFIXES = [
    "private limited",
    "private ltd",
    "pvt limited",
    "pvt ltd",
    "limited",
    "ltd",
    "corporation",
    "corp",
    "incorporated",
    "inc",
    "company",
    "co",
    "llc",
    "llp"
]


def extract_suffix(name):

    name = normalize_name(name)

    for suffix in sorted(SUFFIXES, key=len, reverse=True):

        if name.endswith(" " + suffix):
            return suffix

    return ""

In [23]:
for name in test_names:
    print(name, " -> ", extract_suffix(name))

FQ Social, Inc  ->  inc
FQ Social, Inc.  ->  inc
FQ Social, Ínc  ->  inc
Arcxylo DBA FQ Social, Inc  ->  inc

In [24]:
## create the core names
def extract_core_name(name):

    name = normalize_name(name)

    suffix = extract_suffix(name)

    if suffix:
        name = name[:-len(suffix)].strip()

    return name

In [25]:
sample_pairs["s1_norm"] = sample_pairs["s1_name"].apply(normalize_name)
sample_pairs["matched_norm"] = sample_pairs["matched_name"].apply(normalize_name)

sample_pairs["s1_suffix"] = sample_pairs["s1_name"].apply(extract_suffix)
sample_pairs["matched_suffix"] = sample_pairs["matched_name"].apply(extract_suffix)

sample_pairs["s1_core"] = sample_pairs["s1_name"].apply(extract_core_name)
sample_pairs["matched_core"] = sample_pairs["matched_name"].apply(extract_core_name)

In [26]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "s1_norm",
        "matched_norm",
        "s1_core",
        "matched_core",
        "s1_suffix",
        "matched_suffix"
    ]
].head(20)

,s1_name,matched_name,s1_norm,matched_norm,s1_core,matched_core,s1_suffix,matched_suffix
0,"FQ Social, Inc","FQ Social, Inc.",fq social inc,fq social inc,fq social,fq social,inc,inc
1,"FQ Social, Inc","FQ Social, #42836",fq social inc,fq social 42836,fq social,fq social 42836,inc,
2,"FQ Social, Inc","FQ Social, Ínc",fq social inc,fq social inc,fq social,fq social,inc,inc
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",fq social inc,arcxylo dba fq social inc,fq social,arcxylo dba fq social,inc,inc
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,innovative consultants,,innovative consultants,,,
5,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,innovative consultants,innovative consultants,,
6,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,innovative consultants,innovative consultants,,
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,hyderabad 500060 kumar private limited,hyderabad 500060 kumar,hyderabad 500060 kumar,hyderabad 500060 kumar,private limited,
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,hyderabad 500060 kumar private limited,hyderabad 500060 kumar private limited,hyderabad 500060 kumar,hyderabad 500060 kumar,private limited,private limited
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",bishop melton and schmidt foods,bishop melton and schmidt foods lp,bishop melton and schmidt foods,bishop melton and schmidt foods lp,,
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",bishop melton and schmidt foods,bishop melton and schmidt foods inc,bishop melton and schmidt foods,bishop melton and schmidt foods,,inc
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods,,
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,golden classic fox llc,golden classic llc partners,golden classic fox,golden classic llc partners,llc,
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,golden classic fox llc,golden classic fox llc,golden classic fox,golden classic fox,llc,llc
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",golden classic fox llc,golden fox llc center,golden classic fox,golden fox llc center,llc,
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,reet exports india private limited,reet exports india private limited,reet exports india,reet exports india,private limited,private limited
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,reet exports india private limited,reet exports india limited services,reet exports india,reet exports india limited services,private limited,
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,reet exports india private limited,reet exports india private limited,reet exports india,reet exports india,private limited,private limited
18,Reet Exports (India) Private Limited,reetexportsindia.com,reet exports india private limited,reetexportsindia com,reet exports india,reetexportsindia com,private limited,
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,reet exports india private limited,reet exports india private limited,reet exports india,reet exports india,private limited,private limited

In [27]:
## get better names

def remove_numbers(name):
    if pd.isna(name):
        return ""
    name = str(name)
    # Remove numbers
    name = re.sub(r'\d+', ' ', name)
    # Remove extra spaces
    name = re.sub(r'\s+', ' ', name).strip()
    return name

def get_name_no_numbers(name):
    name = normalize_name(name)

    # Remove numbers
    name = re.sub(r'\d+', ' ', name)

    # Remove extra spaces
    name = re.sub(r'\s+', ' ', name).strip()

    return name

In [28]:
sample_pairs["s1_no_numbers"] = sample_pairs["s1_name"].apply(get_name_no_numbers)

sample_pairs["matched_no_numbers"] = sample_pairs["matched_name"].apply(get_name_no_numbers)

In [29]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "s1_core",
        "matched_core",
        "s1_no_numbers",
        "matched_no_numbers"
    ]
].head(20)

,s1_name,matched_name,s1_core,matched_core,s1_no_numbers,matched_no_numbers
0,"FQ Social, Inc","FQ Social, Inc.",fq social,fq social,fq social inc,fq social inc
1,"FQ Social, Inc","FQ Social, #42836",fq social,fq social 42836,fq social inc,fq social
2,"FQ Social, Inc","FQ Social, Ínc",fq social,fq social,fq social inc,fq social inc
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",fq social,arcxylo dba fq social,fq social inc,arcxylo dba fq social inc
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,innovative consultants,,innovative consultants,
5,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,innovative consultants,innovative consultants
6,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,innovative consultants,innovative consultants
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,hyderabad 500060 kumar,hyderabad 500060 kumar,hyderabad kumar private limited,hyderabad kumar
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,hyderabad 500060 kumar,hyderabad 500060 kumar,hyderabad kumar private limited,hyderabad kumar private limited
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",bishop melton and schmidt foods,bishop melton and schmidt foods lp,bishop melton and schmidt foods,bishop melton and schmidt foods lp
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods inc
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,golden classic fox,golden classic llc partners,golden classic fox llc,golden classic llc partners
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,golden classic fox,golden classic fox,golden classic fox llc,golden classic fox llc
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",golden classic fox,golden fox llc center,golden classic fox llc,golden fox llc center
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,reet exports india,reet exports india,reet exports india private limited,reet exports india private limited
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,reet exports india,reet exports india limited services,reet exports india private limited,reet exports india limited services
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,reet exports india,reet exports india,reet exports india private limited,reet exports india private limited
18,Reet Exports (India) Private Limited,reetexportsindia.com,reet exports india,reetexportsindia com,reet exports india private limited,reetexportsindia com
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,reet exports india,reet exports india,reet exports india private limited,reet exports india private limited

In [30]:
def extract_domain_name(name):

    if pd.isna(name):
        return ""

    name = str(name).lower().strip()

    # Remove protocol
    name = re.sub(r'^https?://', '', name)

    # Remove www.
    name = re.sub(r'^www\.', '', name)

    # Remove path
    name = name.split('/')[0]

    # Check whether it looks like a domain
    if '.' in name:
        parts = name.split('.')

        # Remove common domain extensions
        if parts[-1] in ["com", "org", "net", "in", "co", "biz"]:
            return parts[0]

    return ""

In [31]:
print(extract_domain_name("reetexportsindia.com"))

reetexportsindia

In [32]:
sample_pairs["s1_domain"] = sample_pairs["s1_name"].apply(extract_domain_name)

sample_pairs["matched_domain"] = sample_pairs["matched_name"].apply(extract_domain_name)

In [33]:
sample_pairs[
    [
        "s1_name",
     "matched_name",
     "s1_domain",
     "matched_domain"]
    ].head(30)

,s1_name,matched_name,s1_domain,matched_domain
0,"FQ Social, Inc","FQ Social, Inc.",,
1,"FQ Social, Inc","FQ Social, #42836",,
2,"FQ Social, Inc","FQ Social, Ínc",,
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",,
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,,
5,Innovative Consultants,Innovative Consultants,,
6,Innovative Consultants,Innovative Consultants,,
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,,
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,,
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",,
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",,
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",,
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,,
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,,
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",,
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,,
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,,reet exports (india) limited services | www
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,,
18,Reet Exports (India) Private Limited,reetexportsindia.com,,reetexportsindia
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,,
20,Reet Exports (India) Private Limited,Reet (lndia) Exports Private [Limited],,
21,Brightium Lithium LLC,brightium lithium llc,,
22,Brightium Lithium LLC,Brightium (Lithium),,
23,Life Construction Private Limited,लाइफ कंस्ट्रक्शन प्राइवेट लिमिटेड,,
24,Life Construction Private Limited,Shri Life Construction Private,,
25,Anchor Staking Inc,Anchor Stáking Inc,,
26,Anchor Staking Inc,anchor staking inc,,
27,Anchor Staking Inc,ANCHOR STAKIFNG INC,,
28,Anchor Staking Inc,Anchorstaking.Com,,anchorstaking
29,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,,

In [34]:
sample_pairs.columns

Index(['s1_name', 'matched_name', 's1_address', 'matched_address', 's1_norm',
       'matched_norm', 's1_suffix', 'matched_suffix', 's1_core',
       'matched_core', 's1_no_numbers', 'matched_no_numbers', 's1_domain',
       'matched_domain'],
      dtype='object')

In [35]:
def extract_dba_name(name):

    if pd.isna(name):
        return ""

    name = normalize_name(name)

    match = re.search(r'\bdba\b\s+(.*)', name)

    if match:
        return match.group(1).strip()

    return ""

In [36]:
sample_pairs["s1_dba"] = sample_pairs["s1_name"].apply(extract_dba_name)

sample_pairs["matched_dba"] = sample_pairs["matched_name"].apply(extract_dba_name)

In [37]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "s1_dba",
        "matched_dba"
    ]
].head(20)

,s1_name,matched_name,s1_dba,matched_dba
0,"FQ Social, Inc","FQ Social, Inc.",,
1,"FQ Social, Inc","FQ Social, #42836",,
2,"FQ Social, Inc","FQ Social, Ínc",,
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",,fq social inc
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,,
5,Innovative Consultants,Innovative Consultants,,
6,Innovative Consultants,Innovative Consultants,,
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,,
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,,
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",,
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",,
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",,
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,,
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,,
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",,
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,,
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,,
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,,
18,Reet Exports (India) Private Limited,reetexportsindia.com,,
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,,

In [38]:
## Tf-idf vectorization
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 4)
)

all_names = pd.concat([
    sample_pairs["s1_norm"],
    sample_pairs["matched_norm"]
]).fillna("")

vectorizer.fit(all_names)

s1_vec = vectorizer.transform(sample_pairs["s1_norm"])
matched_vec = vectorizer.transform(sample_pairs["matched_norm"])

sample_pairs["name_tfidf_similarity"] = [
    cosine_similarity(s1_vec[i], matched_vec[i])[0][0]
    for i in range(len(sample_pairs))
]

In [39]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "s1_core",
        "matched_core",
        "name_tfidf_similarity"
    ]
].head(50)

,s1_name,matched_name,s1_core,matched_core,name_tfidf_similarity
0,"FQ Social, Inc","FQ Social, Inc.",fq social,fq social,1.000000
1,"FQ Social, Inc","FQ Social, #42836",fq social,fq social 42836,0.542283
2,"FQ Social, Inc","FQ Social, Ínc",fq social,fq social,1.000000
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",fq social,arcxylo dba fq social,0.554054
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,innovative consultants,,0.000000
5,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,1.000000
6,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,1.000000
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,hyderabad 500060 kumar,hyderabad 500060 kumar,0.918641
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,hyderabad 500060 kumar,hyderabad 500060 kumar,1.000000
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",bishop melton and schmidt foods,bishop melton and schmidt foods lp,0.960665
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",bishop melton and schmidt foods,bishop melton and schmidt foods,0.961956
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",bishop melton and schmidt foods,bishop melton and schmidt foods,1.000000
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,golden classic fox,golden classic llc partners,0.610068
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,golden classic fox,golden classic fox,1.000000
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",golden classic fox,golden fox llc center,0.585539
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,reet exports india,reet exports india,1.000000
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,reet exports india,reet exports india limited services,0.771393
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,reet exports india,reet exports india,1.000000
18,Reet Exports (India) Private Limited,reetexportsindia.com,reet exports india,reetexportsindia com,0.477694
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,reet exports india,reet exports india,1.000000
20,Reet Exports (India) Private Limited,Reet (lndia) Exports Private [Limited],reet exports india,reet lndia exports,0.704353
21,Brightium Lithium LLC,brightium lithium llc,brightium lithium,brightium lithium,1.000000
22,Brightium Lithium LLC,Brightium (Lithium),brightium lithium,brightium lithium,0.946439
23,Life Construction Private Limited,लाइफ कंस्ट्रक्शन प्राइवेट लिमिटेड,life construction,,0.000000
24,Life Construction Private Limited,Shri Life Construction Private,life construction,shri life construction private,0.808229
25,Anchor Staking Inc,Anchor Stáking Inc,anchor staking,anchor staking,1.000000
26,Anchor Staking Inc,anchor staking inc,anchor staking,anchor staking,1.000000
27,Anchor Staking Inc,ANCHOR STAKIFNG INC,anchor staking,anchor stakifng,0.730560
28,Anchor Staking Inc,Anchorstaking.Com,anchor staking,anchorstaking com,0.647610
29,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,bharat infra,,0.000000
30,Bharat Infra Private Limited,Bharat Private Limited Center,bharat infra,bharat private limited center,0.629438
31,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,bharat infra,,0.000000
32,Galaxy Projects Private Limited,గెలాక్సీ Projects Private Limited,galaxy projects,projects,0.753685
33,R K Hernandez Sky LLC,R K HERNANDEZ SKY,r k hernandez sky,r k hernandez sky,0.928595
34,R K Hernandez Sky LLC,R K Hernandez Sky L.L.C.,r k hernandez sky,r k hernandez sky l l c,0.899094
35,R K Hernandez Sky LLC,R K Henandz Sky LLC,r k hernandez sky,r k henandz sky,0.613793
36,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,mukta india india,mukta india india,0.943964
37,Mukta India (India) Pvt Ltd,M/s MUKTA ÍNDIA (INDIA) PVT LTD,mukta india india,m s mukta india india,0.909637
38,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,mukta india india,mukta india india,0.943964
39,Mukta India (India) Pvt Ltd,M/s Mukta India (India) Pvt Limited,mukta india india,m s mukta india india,0.861561
40,Mukta India (India) Pvt Ltd,Mukta (India) Pvt Ltd Partners,mukta india india,mukta india pvt ltd partners,0.766378
41,Macro Food LLP,MACRO FOOD LLP,macro food,macro food,1.000000
42,Macro Food LLP,Macro Food LLP,macro food,macro food,1.000000
43,Macro Food LLP,Fayevionovi,macro food,fayevionovi,0.000000
44,Macro Food LLP,Macr0 Food LLP,macro food,macr0 food,0.577050
45,Macro Food LLP,macro food [llp],macro food,macro food,1.000000
46,Cypress,Cypsres,cypress,cypsres,0.275393
47,Cypress,Cypress,cypress,cypress,1.000000
48,Cypress,CYPRESS,cypress,cypress,1.000000
49,Cypress,Cypress,cypress,cypress,1.000000

In [40]:
core_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 4)
)

all_core_names = pd.concat([
    sample_pairs["s1_core"],
    sample_pairs["matched_core"]
]).fillna("")

core_vectorizer.fit(all_core_names)

s1_core_vec = core_vectorizer.transform(
    sample_pairs["s1_core"]
)

matched_core_vec = core_vectorizer.transform(
    sample_pairs["matched_core"]
)

sample_pairs["core_tfidf_similarity"] = [
    cosine_similarity(
        s1_core_vec[i],
        matched_core_vec[i]
    )[0][0]
    for i in range(len(sample_pairs))
]

In [41]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "name_tfidf_similarity",
        "core_tfidf_similarity"
    ]
].head(50)

,s1_name,matched_name,name_tfidf_similarity,core_tfidf_similarity
0,"FQ Social, Inc","FQ Social, Inc.",1.000000,1.000000
1,"FQ Social, Inc","FQ Social, #42836",0.542283,0.576062
2,"FQ Social, Inc","FQ Social, Ínc",1.000000,1.000000
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",0.554054,0.502757
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,0.000000,0.000000
5,Innovative Consultants,Innovative Consultants,1.000000,1.000000
6,Innovative Consultants,Innovative Consultants,1.000000,1.000000
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,0.918641,1.000000
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,1.000000,1.000000
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",0.960665,0.949757
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",0.961956,1.000000
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",1.000000,1.000000
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,0.610068,0.624118
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,1.000000,1.000000
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",0.585539,0.399530
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,1.000000,1.000000
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,0.771393,0.745512
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,1.000000,1.000000
18,Reet Exports (India) Private Limited,reetexportsindia.com,0.477694,0.499657
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,1.000000,1.000000
20,Reet Exports (India) Private Limited,Reet (lndia) Exports Private [Limited],0.704353,0.597723
21,Brightium Lithium LLC,brightium lithium llc,1.000000,1.000000
22,Brightium Lithium LLC,Brightium (Lithium),0.946439,1.000000
23,Life Construction Private Limited,लाइफ कंस्ट्रक्शन प्राइवेट लिमिटेड,0.000000,0.000000
24,Life Construction Private Limited,Shri Life Construction Private,0.808229,0.723446
25,Anchor Staking Inc,Anchor Stáking Inc,1.000000,1.000000
26,Anchor Staking Inc,anchor staking inc,1.000000,1.000000
27,Anchor Staking Inc,ANCHOR STAKIFNG INC,0.730560,0.715472
28,Anchor Staking Inc,Anchorstaking.Com,0.647610,0.660771
29,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,0.000000,0.000000
30,Bharat Infra Private Limited,Bharat Private Limited Center,0.629438,0.387605
31,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,0.000000,0.000000
32,Galaxy Projects Private Limited,గెలాక్సీ Projects Private Limited,0.753685,0.634606
33,R K Hernandez Sky LLC,R K HERNANDEZ SKY,0.928595,1.000000
34,R K Hernandez Sky LLC,R K Hernandez Sky L.L.C.,0.899094,0.853459
35,R K Hernandez Sky LLC,R K Henandz Sky LLC,0.613793,0.558313
36,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,0.943964,1.000000
37,Mukta India (India) Pvt Ltd,M/s MUKTA ÍNDIA (INDIA) PVT LTD,0.909637,0.892301
38,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,0.943964,1.000000
39,Mukta India (India) Pvt Ltd,M/s Mukta India (India) Pvt Limited,0.861561,0.892301
40,Mukta India (India) Pvt Ltd,Mukta (India) Pvt Ltd Partners,0.766378,0.594866
41,Macro Food LLP,MACRO FOOD LLP,1.000000,1.000000
42,Macro Food LLP,Macro Food LLP,1.000000,1.000000
43,Macro Food LLP,Fayevionovi,0.000000,0.000000
44,Macro Food LLP,Macr0 Food LLP,0.577050,0.448615
45,Macro Food LLP,macro food [llp],1.000000,1.000000
46,Cypress,Cypsres,0.275393,0.274304
47,Cypress,Cypress,1.000000,1.000000
48,Cypress,CYPRESS,1.000000,1.000000
49,Cypress,Cypress,1.000000,1.000000

In [42]:
##Address similarity
# 1. Normalizing address
def normalize_address(address):
    if pd.isna(address):
        return ""

    address = str(address).lower()

    address = re.sub(r'[^\w\s]', ' ', address)
    address = re.sub(r'\s+', ' ', address)

    return address.strip()

In [43]:
##2. creating address columns
sample_pairs["s1_address_norm"] = (
    sample_pairs["s1_address"]
    .apply(normalize_address)
)

sample_pairs["matched_address_norm"] = (
    sample_pairs["matched_address"]
    .apply(normalize_address)
)

In [44]:
##3. TF-IDF address
address_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5)
)

all_addresses = pd.concat([
    sample_pairs["s1_address_norm"],
    sample_pairs["matched_address_norm"]
]).fillna("")

address_vectorizer.fit(all_addresses)

s1_address_vec = address_vectorizer.transform(
    sample_pairs["s1_address_norm"]
)

matched_address_vec = address_vectorizer.transform(
    sample_pairs["matched_address_norm"]
)

In [45]:
sample_pairs["address_tfidf_similarity"] = [
    cosine_similarity(
        s1_address_vec[i],
        matched_address_vec[i]
    )[0][0]
    for i in range(len(sample_pairs))
]

In [46]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "name_tfidf_similarity",
        "core_tfidf_similarity",
        "address_tfidf_similarity"
    ]
].head(50)

,s1_name,matched_name,name_tfidf_similarity,core_tfidf_similarity,address_tfidf_similarity
0,"FQ Social, Inc","FQ Social, Inc.",1.000000,1.000000,1.000000
1,"FQ Social, Inc","FQ Social, #42836",0.542283,0.576062,1.000000
2,"FQ Social, Inc","FQ Social, Ínc",1.000000,1.000000,0.920062
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",0.554054,0.502757,1.000000
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,0.000000,0.000000,0.744837
5,Innovative Consultants,Innovative Consultants,1.000000,1.000000,0.000000
6,Innovative Consultants,Innovative Consultants,1.000000,1.000000,0.958896
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,0.918641,1.000000,0.856416
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,1.000000,1.000000,0.893966
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",0.960665,0.949757,0.380581
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",0.961956,1.000000,0.492059
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",1.000000,1.000000,0.493302
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,0.610068,0.624118,0.694199
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,1.000000,1.000000,0.928433
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",0.585539,0.399530,0.838941
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,1.000000,1.000000,0.944987
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,0.771393,0.745512,0.944987
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,1.000000,1.000000,0.912827
18,Reet Exports (India) Private Limited,reetexportsindia.com,0.477694,0.499657,1.000000
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,1.000000,1.000000,0.580818
20,Reet Exports (India) Private Limited,Reet (lndia) Exports Private [Limited],0.704353,0.597723,0.932583
21,Brightium Lithium LLC,brightium lithium llc,1.000000,1.000000,0.805182
22,Brightium Lithium LLC,Brightium (Lithium),0.946439,1.000000,0.737403
23,Life Construction Private Limited,लाइफ कंस्ट्रक्शन प्राइवेट लिमिटेड,0.000000,0.000000,0.764841
24,Life Construction Private Limited,Shri Life Construction Private,0.808229,0.723446,0.973627
25,Anchor Staking Inc,Anchor Stáking Inc,1.000000,1.000000,0.766423
26,Anchor Staking Inc,anchor staking inc,1.000000,1.000000,0.839164
27,Anchor Staking Inc,ANCHOR STAKIFNG INC,0.730560,0.715472,0.914861
28,Anchor Staking Inc,Anchorstaking.Com,0.647610,0.660771,0.839992
29,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,0.000000,0.000000,0.528430
30,Bharat Infra Private Limited,Bharat Private Limited Center,0.629438,0.387605,0.171604
31,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,0.000000,0.000000,0.171604
32,Galaxy Projects Private Limited,గెలాక్సీ Projects Private Limited,0.753685,0.634606,0.957098
33,R K Hernandez Sky LLC,R K HERNANDEZ SKY,0.928595,1.000000,0.703445
34,R K Hernandez Sky LLC,R K Hernandez Sky L.L.C.,0.899094,0.853459,0.684084
35,R K Hernandez Sky LLC,R K Henandz Sky LLC,0.613793,0.558313,0.392113
36,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,0.943964,1.000000,0.834152
37,Mukta India (India) Pvt Ltd,M/s MUKTA ÍNDIA (INDIA) PVT LTD,0.909637,0.892301,0.700728
38,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,0.943964,1.000000,0.781550
39,Mukta India (India) Pvt Ltd,M/s Mukta India (India) Pvt Limited,0.861561,0.892301,0.674839
40,Mukta India (India) Pvt Ltd,Mukta (India) Pvt Ltd Partners,0.766378,0.594866,0.782146
41,Macro Food LLP,MACRO FOOD LLP,1.000000,1.000000,1.000000
42,Macro Food LLP,Macro Food LLP,1.000000,1.000000,0.460463
43,Macro Food LLP,Fayevionovi,0.000000,0.000000,0.482024
44,Macro Food LLP,Macr0 Food LLP,0.577050,0.448615,0.514603
45,Macro Food LLP,macro food [llp],1.000000,1.000000,0.508724
46,Cypress,Cypsres,0.275393,0.274304,0.902563
47,Cypress,Cypress,1.000000,1.000000,1.000000
48,Cypress,CYPRESS,1.000000,1.000000,1.000000
49,Cypress,Cypress,1.000000,1.000000,0.902563

In [47]:
sample_pairs["combined_score"] = (
    0.45 * sample_pairs["name_tfidf_similarity"]
    + 0.25 * sample_pairs["core_tfidf_similarity"]
    + 0.30 * sample_pairs["address_tfidf_similarity"]
)

In [48]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "name_tfidf_similarity",
        "core_tfidf_similarity",
        "address_tfidf_similarity",
        "combined_score"
    ]
].head(50)

,s1_name,matched_name,name_tfidf_similarity,core_tfidf_similarity,address_tfidf_similarity,combined_score
0,"FQ Social, Inc","FQ Social, Inc.",1.000000,1.000000,1.000000,1.000000
1,"FQ Social, Inc","FQ Social, #42836",0.542283,0.576062,1.000000,0.688043
2,"FQ Social, Inc","FQ Social, Ínc",1.000000,1.000000,0.920062,0.976019
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",0.554054,0.502757,1.000000,0.675013
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,0.000000,0.000000,0.744837,0.223451
5,Innovative Consultants,Innovative Consultants,1.000000,1.000000,0.000000,0.700000
6,Innovative Consultants,Innovative Consultants,1.000000,1.000000,0.958896,0.987669
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,0.918641,1.000000,0.856416,0.920313
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,1.000000,1.000000,0.893966,0.968190
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",0.960665,0.949757,0.380581,0.783913
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",0.961956,1.000000,0.492059,0.830498
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",1.000000,1.000000,0.493302,0.847991
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,0.610068,0.624118,0.694199,0.638820
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,1.000000,1.000000,0.928433,0.978530
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",0.585539,0.399530,0.838941,0.615057
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,1.000000,1.000000,0.944987,0.983496
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,0.771393,0.745512,0.944987,0.817001
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,1.000000,1.000000,0.912827,0.973848
18,Reet Exports (India) Private Limited,reetexportsindia.com,0.477694,0.499657,1.000000,0.639877
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,1.000000,1.000000,0.580818,0.874245
20,Reet Exports (India) Private Limited,Reet (lndia) Exports Private [Limited],0.704353,0.597723,0.932583,0.746165
21,Brightium Lithium LLC,brightium lithium llc,1.000000,1.000000,0.805182,0.941555
22,Brightium Lithium LLC,Brightium (Lithium),0.946439,1.000000,0.737403,0.897119
23,Life Construction Private Limited,लाइफ कंस्ट्रक्शन प्राइवेट लिमिटेड,0.000000,0.000000,0.764841,0.229452
24,Life Construction Private Limited,Shri Life Construction Private,0.808229,0.723446,0.973627,0.836653
25,Anchor Staking Inc,Anchor Stáking Inc,1.000000,1.000000,0.766423,0.929927
26,Anchor Staking Inc,anchor staking inc,1.000000,1.000000,0.839164,0.951749
27,Anchor Staking Inc,ANCHOR STAKIFNG INC,0.730560,0.715472,0.914861,0.782078
28,Anchor Staking Inc,Anchorstaking.Com,0.647610,0.660771,0.839992,0.708615
29,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,0.000000,0.000000,0.528430,0.158529
30,Bharat Infra Private Limited,Bharat Private Limited Center,0.629438,0.387605,0.171604,0.431630
31,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,0.000000,0.000000,0.171604,0.051481
32,Galaxy Projects Private Limited,గెలాక్సీ Projects Private Limited,0.753685,0.634606,0.957098,0.784939
33,R K Hernandez Sky LLC,R K HERNANDEZ SKY,0.928595,1.000000,0.703445,0.878901
34,R K Hernandez Sky LLC,R K Hernandez Sky L.L.C.,0.899094,0.853459,0.684084,0.823182
35,R K Hernandez Sky LLC,R K Henandz Sky LLC,0.613793,0.558313,0.392113,0.533419
36,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,0.943964,1.000000,0.834152,0.925029
37,Mukta India (India) Pvt Ltd,M/s MUKTA ÍNDIA (INDIA) PVT LTD,0.909637,0.892301,0.700728,0.842630
38,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,0.943964,1.000000,0.781550,0.909249
39,Mukta India (India) Pvt Ltd,M/s Mukta India (India) Pvt Limited,0.861561,0.892301,0.674839,0.813230
40,Mukta India (India) Pvt Ltd,Mukta (India) Pvt Ltd Partners,0.766378,0.594866,0.782146,0.728230
41,Macro Food LLP,MACRO FOOD LLP,1.000000,1.000000,1.000000,1.000000
42,Macro Food LLP,Macro Food LLP,1.000000,1.000000,0.460463,0.838139
43,Macro Food LLP,Fayevionovi,0.000000,0.000000,0.482024,0.144607
44,Macro Food LLP,Macr0 Food LLP,0.577050,0.448615,0.514603,0.526207
45,Macro Food LLP,macro food [llp],1.000000,1.000000,0.508724,0.852617
46,Cypress,Cypsres,0.275393,0.274304,0.902563,0.463272
47,Cypress,Cypress,1.000000,1.000000,1.000000,1.000000
48,Cypress,CYPRESS,1.000000,1.000000,1.000000,1.000000
49,Cypress,Cypress,1.000000,1.000000,0.902563,0.970769

In [49]:
#  create ~10000 positive + ~10000 hard negative pairs 
positive_pairs = sample_pairs.copy()

positive_pairs["label"] = 1

In [50]:
print("Positive pairs:", len(positive_pairs))

Positive pairs: 3559

In [51]:
# Create hard negative pairs
import pandas as pd
import numpy as np

s2_sample = s2.sample(
    n=len(positive_pairs),
    random_state=42
).reset_index(drop=True)

s3_sample = s3.sample(
    n=len(positive_pairs),
    random_state=43
).reset_index(drop=True)

In [52]:
# Build a set of true matched IDs
true_match_ids = set()

for value in truth["matched_entity_ids"].dropna():

    ids = str(value).split(",")

    for entity_id in ids:
        entity_id = entity_id.strip()

        if entity_id:
            true_match_ids.add(entity_id)

print("True matched IDs:", len(true_match_ids))

True matched IDs: 7638365

In [53]:
print(sample_pairs.columns.tolist())

['s1_name', 'matched_name', 's1_address', 'matched_address', 's1_norm', 'matched_norm', 's1_suffix', 'matched_suffix', 's1_core', 'matched_core', 's1_no_numbers', 'matched_no_numbers', 's1_domain', 'matched_domain', 's1_dba', 'matched_dba', 'name_tfidf_similarity', 'core_tfidf_similarity', 's1_address_norm', 'matched_address_norm', 'address_tfidf_similarity', 'combined_score']

In [54]:
true_matches = {}

for _, row in truth.iterrows():
    s1_id = row["source1_entity_id"]

    matched_ids = str(row["matched_entity_ids"]).split(",")

    true_matches[s1_id] = {
        x.strip()
        for x in matched_ids
        if x.strip()
    }

In [55]:
s1_sample = s1.sample(
    n=1000,
    random_state=42
).reset_index(drop=True)

In [56]:
# Build country groups ONCE
s2_by_country = {
    country: group
    for country, group in s2.groupby("country")
}

s3_by_country = {
    country: group
    for country, group in s3.groupby("country")
}

print("S2 countries:", len(s2_by_country))
print("S3 countries:", len(s3_by_country))

S2 countries: 2
S3 countries: 2

In [57]:
negative_rows = []

rng = np.random.default_rng(42)

for _, s1_row in s1_sample.iterrows():

    s1_id = s1_row["entity_id"]
    country = s1_row["country"]

    # True matches for THIS S1
    true_ids = true_matches.get(s1_id, set())

    # Get pre-built country groups
    candidates_s2 = s2_by_country.get(country)
    candidates_s3 = s3_by_country.get(country)

    candidate_parts = []

    if candidates_s2 is not None:
        candidate_parts.append(candidates_s2)

    if candidates_s3 is not None:
        candidate_parts.append(candidates_s3)

    if not candidate_parts:
        continue

    candidates = pd.concat(
        candidate_parts,
        ignore_index=True
    )

    # Remove true matches for this S1
    candidates = candidates[
        ~candidates["entity_id"].isin(true_ids)
    ]

    if len(candidates) == 0:
        continue

    # Random negative
    negative = candidates.sample(
        n=1,
        random_state=int(
            rng.integers(0, 1_000_000)
        )
    ).iloc[0]

    negative_rows.append({
        "s1_id": s1_id,
        "s1_name": s1_row["business_name"],
        "s1_address": s1_row["business_address"],
        "s1_country": s1_row["country"],

        "matched_id": negative["entity_id"],
        "matched_name": negative["business_name"],
        "matched_address": negative["business_address"],
        "matched_country": negative["country"],

        "label": 0
    })

negative_pairs = pd.DataFrame(negative_rows)

print("Negative pairs:", len(negative_pairs))

Negative pairs: 1000

In [58]:
negative_pairs = pd.DataFrame(negative_rows)

print("Negative pairs:", len(negative_pairs))

Negative pairs: 1000

In [59]:
positive_rows = []

for _, s1_row in s1_sample.iterrows():

    s1_id = s1_row["entity_id"]

    true_ids = true_matches.get(s1_id, set())

    for matched_id in true_ids:

        if matched_id.startswith("S2-"):
            matched_row = s2_lookup.loc[matched_id]

        elif matched_id.startswith("S3-"):
            matched_row = s3_lookup.loc[matched_id]

        else:
            continue

        positive_rows.append({
            "s1_id": s1_id,
            "s1_name": s1_row["business_name"],
            "s1_address": s1_row["business_address"],
            "s1_country": s1_row["country"],

            "matched_id": matched_id,
            "matched_name": matched_row["business_name"],
            "matched_address": matched_row["business_address"],
            "matched_country": matched_row["country"],

            "label": 1
        })

In [60]:
positive_pairs = pd.DataFrame(positive_rows)

print("Positive pairs:", len(positive_pairs))

Positive pairs: 3451

In [61]:
pairs = pd.concat(
    [positive_pairs, negative_pairs],
    ignore_index=True
)

print(pairs["label"].value_counts())

label
1    3451
0    1000
Name: count, dtype: int64

In [62]:
print(positive_pairs.shape)
print(negative_pairs.shape)
print(pairs["label"].value_counts())

(3451, 9)
(1000, 9)
label
1    3451
0    1000
Name: count, dtype: int64

In [63]:
# Normalize names and addresses
pairs["s1_norm"] = pairs["s1_name"].apply(normalize_name)
pairs["matched_norm"] = pairs["matched_name"].apply(normalize_name)

pairs["s1_core"] = pairs["s1_name"].apply(extract_core_name)
pairs["matched_core"] = pairs["matched_name"].apply(extract_core_name)

pairs["s1_address_norm"] = pairs["s1_address"].apply(normalize_address)
pairs["matched_address_norm"] = pairs["matched_address"].apply(normalize_address)

In [64]:
# Name vectors
s1_vec = vectorizer.transform(pairs["s1_norm"].fillna(""))
matched_vec = vectorizer.transform(pairs["matched_norm"].fillna(""))

# Core-name vectors
s1_core_vec = core_vectorizer.transform(pairs["s1_core"].fillna(""))
matched_core_vec = core_vectorizer.transform(pairs["matched_core"].fillna(""))

# Address vectors
s1_addr_vec = address_vectorizer.transform(
    pairs["s1_address_norm"].fillna("")
)
matched_addr_vec = address_vectorizer.transform(
    pairs["matched_address_norm"].fillna("")
)

In [65]:
pairs["name_tfidf_similarity"] = (
    cosine_similarity(s1_vec, matched_vec).diagonal()
)

pairs["core_tfidf_similarity"] = (
    cosine_similarity(s1_core_vec, matched_core_vec).diagonal()
)

pairs["address_tfidf_similarity"] = (
    cosine_similarity(s1_addr_vec, matched_addr_vec).diagonal()
)

In [66]:
pairs["country_match"] = (
    pairs["s1_country"] == pairs["matched_country"]
).astype(int)

In [67]:
pairs["combined_score"] = (
    0.45 * pairs["name_tfidf_similarity"]
    + 0.25 * pairs["core_tfidf_similarity"]
    + 0.30 * pairs["address_tfidf_similarity"]
)

In [68]:
pairs.groupby("label")[[
    "name_tfidf_similarity",
    "core_tfidf_similarity",
    "address_tfidf_similarity",
    "combined_score"
]].describe()

      name_tfidf_similarity                                               \
                      count      mean       std  min       25%       50%
label
0                    1000.0  0.040457  0.067604  0.0  0.004698  0.016103
1                    3451.0  0.762091  0.282500  0.0  0.674845  0.857609

                         core_tfidf_similarity            ...  \
            75%      max                 count      mean  ...
label                                                     ...
0      0.039653  0.67765                1000.0  0.022865  ...
1      1.000000  1.00000                3451.0  0.768105  ...

      address_tfidf_similarity           combined_score                      \
                           75%       max          count      mean       std
label
0                     0.039383  0.437932         1000.0  0.033500  0.041729
1                     0.885810  1.000000         3451.0  0.752036  0.207933


            min       25%       50%       75%       max
label
0      0.000000  0.010489  0.020486  0.037966  0.442948
1      0.056929  0.672717  0.812614  0.902140  1.000000

[2 rows x 32 columns]

In [69]:
print("Highest scoring NEGATIVES")
display(
    pairs[pairs["label"] == 0]
    .sort_values("combined_score", ascending=False)
    .head(20)
)

print("Lowest scoring POSITIVES")
display(
    pairs[pairs["label"] == 1]
    .sort_values("combined_score")
    .head(20)
)

Highest scoring NEGATIVES

,s1_id,s1_name,s1_address,s1_country,matched_id,matched_name,matched_address,matched_country,label,s1_norm,matched_norm,s1_core,matched_core,s1_address_norm,matched_address_norm,name_tfidf_similarity,core_tfidf_similarity,address_tfidf_similarity,country_match,combined_score
3661,S1-263753520,Silver Industries Private Limited,"House No.65 (Basement), Furniture Block, Kirti Nagar, New Delhi, West Delhi, Delhi",India,S3-247643221,Nm Private Industries Jv Limited,"ఆంధ్రప్రదేశ్, Rajanagaram, 6-32/14., East Godavari, Plot No 123, Ananda Apartments Jagannadhapuram Agraharam",India,0,silver industries private limited,nm private industries jv limited,silver industries,nm private industries jv,house no 65 basement furniture block kirti nagar new delhi west delhi delhi,ఆ ధ రప రద శ rajanagaram 6 32 14 east godavari plot no 123 ananda apartments jagannadhapuram agraharam,0.677650,0.500090,0.043276,1,0.442948
3573,S1-892324295,Rn Brothers Ltd,"K.V.Rangareddy, C/O Rudra Raju Rama Raju, Seri Lingampally, Telangana, Block-2 Flat Number 2608",India,S3-231200546,Sri Vasundhara & Brothers Private,"Building Number #10 Nr Rai Singh Chowk, Gautam Buddha Nagar, Barola, UP",India,0,rn brothers ltd,sri vasundhara brothers private,rn brothers,sri vasundhara brothers private,k v rangareddy c o rudra raju rama raju seri lingampally telangana block 2 flat number 2608,building number 10 nr rai singh chowk gautam buddha nagar barola up,0.438708,0.431102,0.129081,1,0.343918
4278,S1-31505100,Highland Charities,"77 Montauk Highway, Brookhaven, NY",US,S2-308061514,Highland Ashford Llc,"350-352 PINEHAVEN DR, NEW LONDON, NC",US,0,highland charities,highland ashford llc,highland charities,highland ashford,77 montauk highway brookhaven ny,350 352 pinehaven dr new london nc,0.401570,0.429217,0.109823,1,0.320957
3848,S1-145276542,Good Industries,"Flat No. 130 Vrindavan Mukand Staff, Col L B Shastri Marg Ghatkopa Near Pipe Line, Mumbai, Maharashtra",India,S3-38157862,Shakti Sangh Industries LLP,"No 21-C Seva Mandir Road Old Fatehpura, Udaipur, राजस्थान",India,0,good industries,shakti sangh industries llp,good industries,shakti sangh industries,flat no 130 vrindavan mukand staff col l b shastri marg ghatkopa near pipe line mumbai maharashtra,no 21 c seva mandir road old fatehpura udaipur र जस थ न,0.419439,0.432869,0.026782,1,0.304999
3842,S1-138351920,Balaji Pioneer Consultancy Pvt Ltd,"F 802, 8Th Floor, Block -I, Mhb, Sy No-83/1, Raidurgam, Seri Lingampally, K.V.Rangareddy, Telangana",India,S3-948926359,Bharti Consultancy Pbihvte Limited,"Vantage Point, V R M Road, Ravipuram, KL, Ernakulam, C -1, Ernakulam",India,0,balaji pioneer consultancy pvt ltd,bharti consultancy pbihvte limited,balaji pioneer consultancy,bharti consultancy pbihvte,f 802 8th floor block i mhb sy no 83 1 raidurgam seri lingampally k v rangareddy telangana,vantage point v r m road ravipuram kl ernakulam c 1 ernakulam,0.393184,0.344187,0.048541,1,0.277542
4384,S1-927050231,Dental Partners,"3426 Yankee Lane, Mead, WA",US,S2-177436790,Pimentel Atlanta of Montgomery Partners,"195 Pine Crest Lane, NULL, LANSDALE, PA",US,0,dental partners,pimentel atlanta of montgomery partners,dental partners,pimentel atlanta of montgomery partners,3426 yankee lane mead wa,195 pine crest lane null lansdale pa,0.346437,0.341423,0.109129,1,0.273991
4108,S1-382861164,Fortune Finance Private Limited,"Rs No 226, Flat No C-808 Anantpuram Appart Bapat Camp, Kolhapur, Maharashtra",India,S3-793731872,The Modern Finance Pvt Ltd,"Plot No. A-192, Thane, MH",India,0,fortune finance private limited,the modern finance pvt ltd,fortune finance,the modern finance,rs no 226 flat no c 808 anantpuram appart bapat camp kolhapur maharashtra,plot no a 192 thane mh,0.345995,0.362905,0.046114,1,0.260258
4023,S1-139401572,Prakriti India (India) Pvt. Ltd.,"196/18 &19 Ist Floor Aiswarya Commercial Center R S Puram, Coimbatore, Tamil Nadu",India,S3-33633559,Ltd New De1hi India Enterprises,"G 337, New Delhi, DL",India,0,prakriti india india pvt ltd,ltd new de1hi india enterprises,prakriti india india,ltd new de1hi india enterprises,196 18 19 ist floor aiswarya commercial center r s puram coimbatore tamil nadu,g 337 new delhi dl,0.322910,0.326953,0.001061,1,0.227366
4142,S1-961234533,Sierra,"110 750, Bountiful, UT",US,S3-886355556,Verrance Bróokfield,"36 Leo St, Queensbury, New York",US,0,sierra,verrance brookfield,sierra,verrance brookfield,110 750 bountiful ut,36 leo st queensbury new york,0.324602,0.322147,0.000000,1,0.226608
4080,S1-155840225,Exports Saru Services Limited,"C/O Ombeer Singh, Suthyana, Greater Noida, Gautam Budh Nagar, Noida, Gautam Buddha Nagar, Uttar Pradesh",India,S3-936400497,Surat City Solutions Exports Private,"219-B, Surat, ગુજરાત",India,0,exports saru services limited,surat city solutions exports private,exports saru services,surat city solutions exports private,c o ombeer singh suthyana greater noida gautam budh nagar noida gautam buddha nagar uttar pradesh,219 b surat ગ જર ત,0.305828,0.318408,0.013502,1,0.221275
4175,S1-955841937,Chiropractic Center LLC,"Mcalester, 1917 Green Meadows Drive, OK",US,S2-491972835,Smith Practice Family,"GALLAVISTA AVENUE, NASHVILLE, TN",US,0,chiropractic center llc,smith practice family,chiropractic center,smith practice family,mcalester 1917 green meadows drive ok,gallavista avenue nashville tn,0.267738,0.277708,0.013575,1,0.193982
3625,S1-796234929,Gestalt Lifecare (India),"179A, 1St Floor (B/P) Southern Jeewan Nagar, New Delhi, South Delhi, Delhi",India,S2-481085420,ABLE INDIA LIMITED,"DOOR NO G-69 RAJWADA PEARL, 3RD FLOOR FLAT NO 3F, PRATAPGRAH, KOLKATA, KOLKATA, পশ্চিমবঙ্গ",India,0,gestalt lifecare india,able india limited,gestalt lifecare india,able india,179a 1st floor b p southern jeewan nagar new delhi south delhi delhi,door no g 69 rajwada pearl 3rd floor flat no 3f pratapgrah kolkata kolkata পশ চ মবঙ গ,0.236889,0.276864,0.047119,1,0.189951
4345,S1-871380077,Baramati Healthcare Corp,"Shalon Niwas, Vasantnagar, Baramati, Pune, Maharashtra",India,S3-830738628,Wealthhope.Com,"H.no. 200, Gali No. 1, Ward No. 8, Partap Colony Near Allhabad Bank, Patiala, PB",India,0,baramati healthcare corp,wealthhope com,baramati healthcare,wealthhope com,shalon niwas vasantnagar baramati pune maharashtra,h no 200 gali no 1 ward no 8 partap colony near allhabad bank patiala pb,0.270657,0.205984,0.049839,1,0.188243
3664,S1-291922534,Patriot Veterinary Clinic,"6820 Vista Terraza Drive, Albuquerque, NM",US,S3-251471478,Stella Forsl Patriot Shanghai Inc,"679 Nathan Street, Alabama, Alexander City",US,0,patriot veterinary clinic,stella forsl patriot shanghai inc,patriot veterinary clinic,stella forsl patriot shanghai,6820 vista terraza drive albuquerque nm,679 nathan street alabama alexander city,0.253654,0.260893,0.022614,1,0.186152
4051,S1-586172272,Red Technology Private Limited,"B/2/268, Madhuvrund Society, Swi Park, Nr Gopal Bag Soc, Neelkhanth Mahadev Man, Dir Road, Ahmedabad, Gujarat",India,S2-889502603,INDIA NEW ENERGY PRIVATE LIMITED,"B 3 4 SUNY MARKET, MSH MAHESANA, MAHESANA, Gujarat",India,0,red technology private limited,india new energy private limited,red technology,india new energy,b 2 268 madhuvrund society swi park nr gopal bag soc neelkhanth mahadev man dir road ahmedabad gujarat,b 3 4 suny market msh mahesana mahesana gujarat,0.311165,0.019353,0.128214,1,0.183327
3567,S1-902829449,East Properties Private Limited,"428, Mastermind1, I.T Park, Royal Palms, Aarey Colony, Goregaon East, Mumbai, Mumbai City, Maharashtra",India,S3-191231629,Tech Private Limited Services,"At V.i.p Colony Jamui, East Region Bhagalpur, Jamui, BR",India,0,east properties private limited,tech private limited services,east properties,tech private limited services,428 mastermind1 i t park royal palms aarey colony goregaon east mumbai mumbai city maharashtra,at v i p colony jamui east region bhagalpur jamui br,0.288892,0.036645,0.146575,1,0.183135
3941,S1-450618700,Silver Consulting Pvt Ltd,"8-10/41-42 Elango Nagar 2Nd Street, P N Road, Tiruppur, Coimbatore, Tamil Nadu",India,S2-4030935,UNIVERSAL MÁRKETING PVT LTD,"Gujarat, 215, SAHYOG CHEMBARS, KOHINOOR ROAD, SARCAR CHAUK MINI BAZAR, VARACHHA ROAD",India,0,silver consulting pvt ltd,universal marketing pvt ltd,silver consulting,universal marketing,8 10 41 42 elango nagar 2nd street p n road tiruppur coimbatore tamil nadu,gujarat 215 sahyog chembars kohinoor road sarcar chauk mini bazar varachha road,0.310138,0.105489,0.055423,1,0.182561
4194,S1-969403285,Nagindas Master Road Services Private Limited,"301, Gundecha Chambers, Nagindas Master Road, Mumbai, Maharashtra",India,S3-578766145,Limited Indo Consulting Services,"22, Mandakini Enclave Kalkaji, New Delhi, South Delhi, DL",India,0,nagindas master road services private limited,limited indo consulting services,nagindas master road services,limited indo consulting services,301 gundecha chambers nagindas master road mumbai maharashtra,22 mandakini enclave kalkaji new delhi south delhi dl,0.261079,0.213342,0.027758,1,0.179148
3930,S1-25666003,Barnett Gulf Leapfrog Associates,"Washington Court House, 508 Rawling Street, OH",US,S3-146988260,Pediatric Dental Choice Associates [Ltd],"5914- Oakridge Rd, New York, Aubburn",US,0,barnett gulf leapfrog associates,pediatric dental choice associates ltd,barnett gulf leapfrog associates,pediatric dental choice associates,washington court house 508 rawling street oh,5914 oakridge rd new york aubburn,0.222432,0.234950,0.007476,1,0.161075
3575,S1-710139409,EGM Technica Private Limited,"Plot No: 262/B, Sri Ram Nagar, Serilingampally, K.V.Rangareddy, Telangana",India,S3-588402873,Jay Private Limited Center,"H. No. 3-12-118, Ps Colony Ramanthapur, Hyderabad, TG",India,0,egm technica private limited,jay private limited center,egm technica,jay private limited center,plot no 262 b sri ram nagar serilingampally k v rangareddy telangana,h no 3 12 118 ps colony ramanthapur hyderabad tg,0.318589,0.017521,0.042009,1,0.160348

Lowest scoring POSITIVES

,s1_id,s1_name,s1_address,s1_country,matched_id,matched_name,matched_address,matched_country,label,s1_norm,matched_norm,s1_core,matched_core,s1_address_norm,matched_address_norm,name_tfidf_similarity,core_tfidf_similarity,address_tfidf_similarity,country_match,combined_score
2328,S1-785596927,Ganpati & Co,"Level 5, Dnyanvatsal Complex, Opp. Vandevi Mandir, Karve Nagar, Pune, Maharashtra",India,S3-110844528,Smt Gsanaptit and Co #56067,"H.no 546 Lecel 5, Pune, महाराष्ट्र",India,1,ganpati co,smt gsanaptit and co 56067,ganpati,smt gsanaptit and co 56067,level 5 dnyanvatsal complex opp vandevi mandir karve nagar pune maharashtra,h no 546 lecel 5 pune मह र ष ट र,0.033782,0.02004,0.122392,1,0.056929
2534,S1-209008446,Bharat Food Private Limited,"Flat No.701, A Wing Ambika Plaza, 90 Feet Road, Mulund (E), Mumbai, Maharashtra",India,S3-353524462,भारत फूड प्राइवेट लिमिटेड,"#G-701, Mulund (E), महाराष्ट्र",India,1,bharat food private limited,,bharat food,,flat no 701 a wing ambika plaza 90 feet road mulund e mumbai maharashtra,g 701 mulund e मह र ष ट र,0.000000,0.00000,0.202666,1,0.060800
2337,S1-489543846,Shakti Logistics Private Limited,"Plot No. Rb-500, Riico, Industries Area Karoli, Tizara, Alwar, Rajasthan",India,S3-966650162,शक्ति लॉजिस्टिक्स प्राइवेट लिमिटेड,"Plot No. Rb-50, Tizara, Tapokda, राजस्थान",India,1,shakti logistics private limited,,shakti logistics,,plot no rb 500 riico industries area karoli tizara alwar rajasthan,plot no rb 50 tizara tapokda र जस थ न,0.000000,0.00000,0.213859,1,0.064158
32,S1-97176033,Lakshmi Consultants Private Limited,"A-301, New Sai Dham Chsl, Ramdev Park Road, Thane, Maharashtra",India,S3-581985190,लक्ष्मी कंसल्टेंट्स प्राइवेट लिमिटेड,"A-301, Thane, महाराष्ट्र",India,1,lakshmi consultants private limited,,lakshmi consultants,,a 301 new sai dham chsl ramdev park road thane maharashtra,a 301 thane मह र ष ट र,0.000000,0.00000,0.216350,1,0.064905
2963,S1-701583396,Shivam Builders,"Flat No. N1, Mathosree Apartments, Plotno.376, 376/B, Road No.82, Jubileehills, Hyderabad, Telangana",India,S3-193946989,శివం బిల్డర్స్,"తెలంగాణ, Guntur, Hyderabad, Flat No. N1",India,1,shivam builders,,shivam builders,,flat no n1 mathosree apartments plotno 376 376 b road no 82 jubileehills hyderabad telangana,త ల గ ణ guntur hyderabad flat no n1,0.000000,0.00000,0.241097,1,0.072329
876,S1-24424354,Bharat Foundation Private Limited,"E-11, Ram Path, Shyam Nagar Extension, New Sanganer Road, Jaipur, Rajasthan, Jaipur",India,S3-862089762,भारत फाउंडेशन प्राइवेट लिमिटेड,"E-1-1, Jaipur, NULL, RJ",India,1,bharat foundation private limited,,bharat foundation,,e 11 ram path shyam nagar extension new sanganer road jaipur rajasthan jaipur,e 1 1 jaipur null rj,0.000000,0.00000,0.249074,1,0.074722
1308,S1-373896077,Great Surya Consulting Private Limited,"Kanchan, Streetno.2, Madhavpark-2, Nr. Goverdhan Chowk, Rajkot, Gujarat",India,S3-105954325,ગ્રેટ સૂર્ય કન્સલ્ટિંગ પ્રાઇવેટ લિમિટેડ,"Door No 350 Kanchan, Rajkot, ગુજરાત",India,1,great surya consulting private limited,,great surya consulting,,kanchan streetno 2 madhavpark 2 nr goverdhan chowk rajkot gujarat,door no 350 kanchan rajkot ગ જર ત,0.000000,0.00000,0.263428,1,0.079028
937,S1-36216088,Urban Food Private Limited,"Flat No.504/A, 5Th Floor, Plot No.1-98/4/1-13, 28&29, Image Garden Road Jain Sadguru Image S Capital Park Madhapur Village Serilingampally, Shaikpet, Hyderabad, Telangana",India,S2-418857877,అర్బన్ ఫుడ్ ప్రైవేట్ లిమిటెడ్,"HYDERABAD, Telangana, RANGAREDDI, FLAT NO.506/A",India,1,urban food private limited,,urban food,,flat no 504 a 5th floor plot no 1 98 4 1 13 28 29 image garden road jain sadguru image s capital park madhapur village serilingampally shaikpet hyderabad telangana,hyderabad telangana rangareddi flat no 506 a,0.000000,0.00000,0.267161,1,0.080148
479,S1-792705717,Anderson Floating,"866 30th Avenue, Santa Cruz, CA",US,S3-252526966,Jaxxyl0,"866 30th Avenue, Pleasure Point, California",US,1,anderson floating,jaxxyl0,anderson floating,jaxxyl0,866 30th avenue santa cruz ca,866 30th avenue pleasure point california,0.000000,0.00000,0.279722,1,0.083917
437,S1-94703561,Pramod College Private Limited,"Room No. 602, 6Th Floor Gaikwad Heights, Beside Bhagirathi, Thane, Maharashtra",India,S3-768916154,Dr Zephsyn,"Room No. 602, Thane, महाराष्ट्र",India,1,pramod college private limited,dr zephsyn,pramod college,dr zephsyn,room no 602 6th floor gaikwad heights beside bhagirathi thane maharashtra,room no 602 thane मह र ष ट र,0.000000,0.00000,0.320480,1,0.096144
2264,S1-382861164,Fortune Finance Private Limited,"Rs No 226, Flat No C-808 Anantpuram Appart Bapat Camp, Kolhapur, Maharashtra",India,S2-957263226,फॉर्च्यून फाइनेंस प्राइवेट लिमिटेड,"RS NO D/226, KOLHAPUR, महाराष्ट्र",India,1,fortune finance private limited,,fortune finance,,rs no 226 flat no c 808 anantpuram appart bapat camp kolhapur maharashtra,rs no d 226 kolhapur मह र ष ट र,0.000000,0.00000,0.330129,1,0.099039
1220,S1-347000383,Sunrise Construction Private Limited,"4Th Floor, C Wing, Trade World Kamala Mills Compound, S.B. Marg, Lower P, Arel, Mumbai, Mumbai City, Maharashtra",India,S2-389980705,सनराइज कंस्ट्रक्शन प्राइवेट लिमिटेड,"H.NO D/4TH FLOOR, MUMBAI, MUMBAI CITY, महाराष्ट्र",India,1,sunrise construction private limited,,sunrise construction,,4th floor c wing trade world kamala mills compound s b marg lower p arel mumbai mumbai city maharashtra,h no d 4th floor mumbai mumbai city मह र ष ट र,0.000000,0.00000,0.343736,1,0.103121
130,S1-680416224,Tech Infotech Private Limited,"Sri Siddi Vinayaka Apartm, Telangana, Karimnagar, Karim Nagar, 8-6-375/3/8",India,S2-211421430,టెక్ ఇన్ఫోటెక్ ప్రైవేట్ లిమిటెడ్,"HYDERABAD, KARIMNAGAR, తెలంగాణ, 8-6-375/3/8",India,1,tech infotech private limited,,tech infotech,,sri siddi vinayaka apartm telangana karimnagar karim nagar 8 6 375 3 8,hyderabad karimnagar త ల గ ణ 8 6 375 3 8,0.000000,0.00000,0.353389,1,0.106017
1168,S1-387211283,Royal Engineering LLP,"Level - 2, Elegance Tower District Center, Jasola, New Delhi, South Delhi, Delhi",India,S3-624697545,रॉयल इंजीनियरिंग एलएलपी,"H.no 451 Level - 2, New Delhi, DL",India,1,royal engineering llp,,royal engineering,,level 2 elegance tower district center jasola new delhi south delhi delhi,h no 451 level 2 new delhi dl,0.000000,0.00000,0.357629,1,0.107289
1359,S1-661546405,Silver Engineering Private Limited,"Riaz Garden, Old No. 12, New No 29, Kodambakkam High Road, Chennai, Tamil Nadu",India,S3-370440733,சில்வர் இன்ஜினியரிங் பிரைவேட் லிமிடெட்,"Riaz Garden, Chennai, TN",India,1,silver engineering private limited,,silver engineering,,riaz garden old no 12 new no 29 kodambakkam high road chennai tamil nadu,riaz garden chennai tn,0.000000,0.00000,0.357948,1,0.107384
2350,S1-103306793,Swastik Management,"Flat No. 1006, 10Th Floor Block C, Hig Flats, Sec 29, Rohini, Delhi, West Delhi, Delhi",India,S3-658852159,स्वस्तिक मैनेजमेंट,"Flat No. 1006, Delhi, दिल्ली",India,1,swastik management,,swastik management,,flat no 1006 10th floor block c hig flats sec 29 rohini delhi west delhi delhi,flat no 1006 delhi द ल ल,0.000000,0.00000,0.360078,1,0.108023
22,S1-796421498,Creative Projects Limited,"12Thfloor, C, 1204, Roya Oasis, Jankalyan Nagarmalvani, Nr Billabong School, Malad W, Mumbai, Mumbai City, Maharashtra",India,S3-14934788,क्रिएटिव प्रोजेक्ट्स लिमिटेड,"12Thfloor/1, Mumbai, Mumbai City, महाराष्ट्र",India,1,creative projects limited,,creative projects,,12thfloor c 1204 roya oasis jankalyan nagarmalvani nr billabong school malad w mumbai mumbai city maharashtra,12thfloor 1 mumbai mumbai city मह र ष ट र,0.000000,0.00000,0.361734,1,0.108520
2578,S1-226090714,Star Infra Private Limited,"1/440, Vadakkancherry P.O.Trichur Dist, Thalapilly, Thrissur, Kerala",India,S3-796332798,സ്റ്റാർ ഇൻഫ്ര പ്രൈവറ്റ് ലിമിറ്റഡ്,"1/440, Thalapilly, KL",India,1,star infra private limited,,star infra,,1 440 vadakkancherry p o trichur dist thalapilly thrissur kerala,1 440 thalapilly kl,0.000000,0.00000,0.362158,1,0.108647
131,S1-680416224,Tech Infotech Private Limited,"Sri Siddi Vinayaka Apartm, Telangana, Karimnagar, Karim Nagar, 8-6-375/3/8",India,S2-157721942,టెక్ ఇన్ఫోటెక్ ప్రైవేట్ లిమిటెడ్,"8-6-375/3/8, KARIMNAGAR, HYDERABAD, తెలంగాణ",India,1,tech infotech private limited,,tech infotech,,sri siddi vinayaka apartm telangana karimnagar karim nagar 8 6 375 3 8,8 6 375 3 8 karimnagar hyderabad త ల గ ణ,0.000000,0.00000,0.363833,1,0.109150
2554,S1-938180046,Vista Solutions Private Limited,"B-88, Gf-3, Ramprastha Colony, Ghaziabad, Uttar Pradesh",India,S3-887255272,Fayelyracira,"No. 796 B-88, Ghaziabad, UP",India,1,vista solutions private limited,fayelyracira,vista solutions,fayelyracira,b 88 gf 3 ramprastha colony ghaziabad uttar pradesh,no 796 b 88 ghaziabad up,0.000000,0.00000,0.365865,1,0.109759

In [70]:
print("POSITIVE PAIRS")
display(
    pairs[pairs["label"] == 1][[
        "s1_name",
        "matched_name",
        "name_tfidf_similarity",
        "core_tfidf_similarity",
        "address_tfidf_similarity",
        "combined_score"
    ]]
    .sort_values("combined_score")
    .head(30)
)

POSITIVE PAIRS

,s1_name,matched_name,name_tfidf_similarity,core_tfidf_similarity,address_tfidf_similarity,combined_score
2328,Ganpati & Co,Smt Gsanaptit and Co #56067,0.033782,0.02004,0.122392,0.056929
2534,Bharat Food Private Limited,भारत फूड प्राइवेट लिमिटेड,0.000000,0.00000,0.202666,0.060800
2337,Shakti Logistics Private Limited,शक्ति लॉजिस्टिक्स प्राइवेट लिमिटेड,0.000000,0.00000,0.213859,0.064158
32,Lakshmi Consultants Private Limited,लक्ष्मी कंसल्टेंट्स प्राइवेट लिमिटेड,0.000000,0.00000,0.216350,0.064905
2963,Shivam Builders,శివం బిల్డర్స్,0.000000,0.00000,0.241097,0.072329
876,Bharat Foundation Private Limited,भारत फाउंडेशन प्राइवेट लिमिटेड,0.000000,0.00000,0.249074,0.074722
1308,Great Surya Consulting Private Limited,ગ્રેટ સૂર્ય કન્સલ્ટિંગ પ્રાઇવેટ લિમિટેડ,0.000000,0.00000,0.263428,0.079028
937,Urban Food Private Limited,అర్బన్ ఫుడ్ ప్రైవేట్ లిమిటెడ్,0.000000,0.00000,0.267161,0.080148
479,Anderson Floating,Jaxxyl0,0.000000,0.00000,0.279722,0.083917
437,Pramod College Private Limited,Dr Zephsyn,0.000000,0.00000,0.320480,0.096144
2264,Fortune Finance Private Limited,फॉर्च्यून फाइनेंस प्राइवेट लिमिटेड,0.000000,0.00000,0.330129,0.099039
1220,Sunrise Construction Private Limited,सनराइज कंस्ट्रक्शन प्राइवेट लिमिटेड,0.000000,0.00000,0.343736,0.103121
130,Tech Infotech Private Limited,టెక్ ఇన్ఫోటెక్ ప్రైవేట్ లిమిటెడ్,0.000000,0.00000,0.353389,0.106017
1168,Royal Engineering LLP,रॉयल इंजीनियरिंग एलएलपी,0.000000,0.00000,0.357629,0.107289
1359,Silver Engineering Private Limited,சில்வர் இன்ஜினியரிங் பிரைவேட் லிமிடெட்,0.000000,0.00000,0.357948,0.107384
2350,Swastik Management,स्वस्तिक मैनेजमेंट,0.000000,0.00000,0.360078,0.108023
22,Creative Projects Limited,क्रिएटिव प्रोजेक्ट्स लिमिटेड,0.000000,0.00000,0.361734,0.108520
2578,Star Infra Private Limited,സ്റ്റാർ ഇൻഫ്ര പ്രൈവറ്റ് ലിമിറ്റഡ്,0.000000,0.00000,0.362158,0.108647
131,Tech Infotech Private Limited,టెక్ ఇన్ఫోటెక్ ప్రైవేట్ లిమిటెడ్,0.000000,0.00000,0.363833,0.109150
2554,Vista Solutions Private Limited,Fayelyracira,0.000000,0.00000,0.365865,0.109759
448,Alpha Tech Private Limited,ఆల్ఫా టెక్ ప్రైవేట్ లిమిటెడ్,0.000000,0.00000,0.366865,0.110060
470,Smart Management Private Limited,ಸ್ಮಾರ್ಟ್ ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,0.00000,0.370274,0.111082
281,Bright Systems Private Limited,ಬ್ರೈಟ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,0.00000,0.378868,0.113660
494,Krishna Finance,कृष्ण फाइनेंस,0.000000,0.00000,0.388403,0.116521
493,Krishna Finance,कृष्णा फाइनेंस,0.000000,0.00000,0.388403,0.116521
398,Raj Global Limited,राज ग्लोबल लिमिटेड,0.000000,0.00000,0.392915,0.117875
280,Bright Systems Private Limited,ಬ್ರೈಟ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,0.00000,0.398071,0.119421
2421,Anand Engineering Private Limited,आनंद इंजीनियरिंग प्राइवेट लिमिटेड,0.000000,0.00000,0.402669,0.120801
96,Ss Construction Private Limited,एसएस कंस्ट्रक्शन प्राइवेट लिमिटेड,0.000000,0.00000,0.402812,0.120844
1191,My Foundation Private Limited,माय फाउंडेशन प्राइवेट लिमिटेड,0.000000,0.00000,0.403216,0.120965

In [71]:
print("Positive score statistics")
print(
    pairs[pairs["label"] == 1][[
        "name_tfidf_similarity",
        "core_tfidf_similarity",
        "address_tfidf_similarity",
        "combined_score"
    ]].describe()
)

Positive score statistics
       name_tfidf_similarity  core_tfidf_similarity  address_tfidf_similarity  \
count            3451.000000            3451.000000               3451.000000
mean                0.762091               0.768105                  0.723563
std                 0.282500               0.298677                  0.232957
min                 0.000000               0.000000                  0.000000
25%                 0.674845               0.662916                  0.631762
50%                 0.857609               0.865175                  0.776529
75%                 1.000000               1.000000                  0.885810
max                 1.000000               1.000000                  1.000000

       combined_score
count     3451.000000
mean         0.752036
std          0.207933
min          0.056929
25%          0.672717
50%          0.812614
75%          0.902140
max          1.000000

In [72]:
print("LOWEST 30 POSITIVES")

display(
    pairs[pairs["label"] == 1][[
        "s1_name",
        "matched_name",
        "s1_address",
        "matched_address",
        "name_tfidf_similarity",
        "core_tfidf_similarity",
        "address_tfidf_similarity",
        "combined_score"
    ]]
    .sort_values("combined_score")
    .head(30)
)

LOWEST 30 POSITIVES

,s1_name,matched_name,s1_address,matched_address,name_tfidf_similarity,core_tfidf_similarity,address_tfidf_similarity,combined_score
2328,Ganpati & Co,Smt Gsanaptit and Co #56067,"Level 5, Dnyanvatsal Complex, Opp. Vandevi Mandir, Karve Nagar, Pune, Maharashtra","H.no 546 Lecel 5, Pune, महाराष्ट्र",0.033782,0.02004,0.122392,0.056929
2534,Bharat Food Private Limited,भारत फूड प्राइवेट लिमिटेड,"Flat No.701, A Wing Ambika Plaza, 90 Feet Road, Mulund (E), Mumbai, Maharashtra","#G-701, Mulund (E), महाराष्ट्र",0.000000,0.00000,0.202666,0.060800
2337,Shakti Logistics Private Limited,शक्ति लॉजिस्टिक्स प्राइवेट लिमिटेड,"Plot No. Rb-500, Riico, Industries Area Karoli, Tizara, Alwar, Rajasthan","Plot No. Rb-50, Tizara, Tapokda, राजस्थान",0.000000,0.00000,0.213859,0.064158
32,Lakshmi Consultants Private Limited,लक्ष्मी कंसल्टेंट्स प्राइवेट लिमिटेड,"A-301, New Sai Dham Chsl, Ramdev Park Road, Thane, Maharashtra","A-301, Thane, महाराष्ट्र",0.000000,0.00000,0.216350,0.064905
2963,Shivam Builders,శివం బిల్డర్స్,"Flat No. N1, Mathosree Apartments, Plotno.376, 376/B, Road No.82, Jubileehills, Hyderabad, Telangana","తెలంగాణ, Guntur, Hyderabad, Flat No. N1",0.000000,0.00000,0.241097,0.072329
876,Bharat Foundation Private Limited,भारत फाउंडेशन प्राइवेट लिमिटेड,"E-11, Ram Path, Shyam Nagar Extension, New Sanganer Road, Jaipur, Rajasthan, Jaipur","E-1-1, Jaipur, NULL, RJ",0.000000,0.00000,0.249074,0.074722
1308,Great Surya Consulting Private Limited,ગ્રેટ સૂર્ય કન્સલ્ટિંગ પ્રાઇવેટ લિમિટેડ,"Kanchan, Streetno.2, Madhavpark-2, Nr. Goverdhan Chowk, Rajkot, Gujarat","Door No 350 Kanchan, Rajkot, ગુજરાત",0.000000,0.00000,0.263428,0.079028
937,Urban Food Private Limited,అర్బన్ ఫుడ్ ప్రైవేట్ లిమిటెడ్,"Flat No.504/A, 5Th Floor, Plot No.1-98/4/1-13, 28&29, Image Garden Road Jain Sadguru Image S Capital Park Madhapur Village Serilingampally, Shaikpet, Hyderabad, Telangana","HYDERABAD, Telangana, RANGAREDDI, FLAT NO.506/A",0.000000,0.00000,0.267161,0.080148
479,Anderson Floating,Jaxxyl0,"866 30th Avenue, Santa Cruz, CA","866 30th Avenue, Pleasure Point, California",0.000000,0.00000,0.279722,0.083917
437,Pramod College Private Limited,Dr Zephsyn,"Room No. 602, 6Th Floor Gaikwad Heights, Beside Bhagirathi, Thane, Maharashtra","Room No. 602, Thane, महाराष्ट्र",0.000000,0.00000,0.320480,0.096144
2264,Fortune Finance Private Limited,फॉर्च्यून फाइनेंस प्राइवेट लिमिटेड,"Rs No 226, Flat No C-808 Anantpuram Appart Bapat Camp, Kolhapur, Maharashtra","RS NO D/226, KOLHAPUR, महाराष्ट्र",0.000000,0.00000,0.330129,0.099039
1220,Sunrise Construction Private Limited,सनराइज कंस्ट्रक्शन प्राइवेट लिमिटेड,"4Th Floor, C Wing, Trade World Kamala Mills Compound, S.B. Marg, Lower P, Arel, Mumbai, Mumbai City, Maharashtra","H.NO D/4TH FLOOR, MUMBAI, MUMBAI CITY, महाराष्ट्र",0.000000,0.00000,0.343736,0.103121
130,Tech Infotech Private Limited,టెక్ ఇన్ఫోటెక్ ప్రైవేట్ లిమిటెడ్,"Sri Siddi Vinayaka Apartm, Telangana, Karimnagar, Karim Nagar, 8-6-375/3/8","HYDERABAD, KARIMNAGAR, తెలంగాణ, 8-6-375/3/8",0.000000,0.00000,0.353389,0.106017
1168,Royal Engineering LLP,रॉयल इंजीनियरिंग एलएलपी,"Level - 2, Elegance Tower District Center, Jasola, New Delhi, South Delhi, Delhi","H.no 451 Level - 2, New Delhi, DL",0.000000,0.00000,0.357629,0.107289
1359,Silver Engineering Private Limited,சில்வர் இன்ஜினியரிங் பிரைவேட் லிமிடெட்,"Riaz Garden, Old No. 12, New No 29, Kodambakkam High Road, Chennai, Tamil Nadu","Riaz Garden, Chennai, TN",0.000000,0.00000,0.357948,0.107384
2350,Swastik Management,स्वस्तिक मैनेजमेंट,"Flat No. 1006, 10Th Floor Block C, Hig Flats, Sec 29, Rohini, Delhi, West Delhi, Delhi","Flat No. 1006, Delhi, दिल्ली",0.000000,0.00000,0.360078,0.108023
22,Creative Projects Limited,क्रिएटिव प्रोजेक्ट्स लिमिटेड,"12Thfloor, C, 1204, Roya Oasis, Jankalyan Nagarmalvani, Nr Billabong School, Malad W, Mumbai, Mumbai City, Maharashtra","12Thfloor/1, Mumbai, Mumbai City, महाराष्ट्र",0.000000,0.00000,0.361734,0.108520
2578,Star Infra Private Limited,സ്റ്റാർ ഇൻഫ്ര പ്രൈവറ്റ് ലിമിറ്റഡ്,"1/440, Vadakkancherry P.O.Trichur Dist, Thalapilly, Thrissur, Kerala","1/440, Thalapilly, KL",0.000000,0.00000,0.362158,0.108647
131,Tech Infotech Private Limited,టెక్ ఇన్ఫోటెక్ ప్రైవేట్ లిమిటెడ్,"Sri Siddi Vinayaka Apartm, Telangana, Karimnagar, Karim Nagar, 8-6-375/3/8","8-6-375/3/8, KARIMNAGAR, HYDERABAD, తెలంగాణ",0.000000,0.00000,0.363833,0.109150
2554,Vista Solutions Private Limited,Fayelyracira,"B-88, Gf-3, Ramprastha Colony, Ghaziabad, Uttar Pradesh","No. 796 B-88, Ghaziabad, UP",0.000000,0.00000,0.365865,0.109759
448,Alpha Tech Private Limited,ఆల్ఫా టెక్ ప్రైవేట్ లిమిటెడ్,"Sy No. 449/E, Dommara Pochampally Medchal-Malkajgiri District, Hyderabad, Telangana","HYDERABAD, Telangana, SY NO. 4-49/E",0.000000,0.00000,0.366865,0.110060
470,Smart Management Private Limited,ಸ್ಮಾರ್ಟ್ ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,"Flatno.201, D.No.562/2-12, H I G House, Bangalore North, Bangalore, Karnataka","H.NO 201, BENGALURU HQ REGION, BANGALORE, Karnataka",0.000000,0.00000,0.370274,0.111082
281,Bright Systems Private Limited,ಬ್ರೈಟ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,"1St Floor, Shree Krishna Akshaya Mansion Complex No.9, 27Th Main, Btm 1St Stage, Bengaluru, Bangalore, Karnataka","H.NO 1ST FLOR, BENGALURU, BANGALORE, ಕರ್ನಾಟಕ",0.000000,0.00000,0.378868,0.113660
494,Krishna Finance,कृष्ण फाइनेंस,"Bld.B Flat-403, Apostrophe Sno.174/4/5/1, Wakad, Pune, Maharashtra","BLD.B FLAT-403, PUNE, महाराष्ट्र",0.000000,0.00000,0.388403,0.116521
493,Krishna Finance,कृष्णा फाइनेंस,"Bld.B Flat-403, Apostrophe Sno.174/4/5/1, Wakad, Pune, Maharashtra","BLD.B FLAT-403, PUNE, महाराष्ट्र",0.000000,0.00000,0.388403,0.116521
398,Raj Global Limited,राज ग्लोबल लिमिटेड,"611 - A, Tulsiani Chambers, Nariman Point, Mumbai, Mumbai City, Maharashtra","महाराष्ट्र, MUMBAI, MUMBAI CITY, 61 - A",0.000000,0.00000,0.392915,0.117875
280,Bright Systems Private Limited,ಬ್ರೈಟ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,"1St Floor, Shree Krishna Akshaya Mansion Complex No.9, 27Th Main, Btm 1St Stage, Bengaluru, Bangalore, Karnataka","1ST FLOOR, BENGALURU, BANGALORE, ಕರ್ನಾಟಕ",0.000000,0.00000,0.398071,0.119421
2421,Anand Engineering Private Limited,आनंद इंजीनियरिंग प्राइवेट लिमिटेड,"26, Silarpur, Near Secretariat, Mandi Ateli, Rewari, Haryana","26, REWARI, हरियाणा, MANDI ATELI",0.000000,0.00000,0.402669,0.120801
96,Ss Construction Private Limited,एसएस कंस्ट्रक्शन प्राइवेट लिमिटेड,"Flat No. 904, 'A' Wing, Pristine Fontana Building S. No. 22, Behind Maratha Mandir, Bavdha, N Khurd, Pune, Maharashtra","FLAT NO. 904, PUNE, Maharashtra",0.000000,0.00000,0.402812,0.120844
1191,My Foundation Private Limited,माय फाउंडेशन प्राइवेट लिमिटेड,"Plot No-15A, New Township, Faridabad, Haryana","PLOT NO-A-15A, FARIDABAD, हरियाणा",0.000000,0.00000,0.403216,0.120965

In [73]:
def token_overlap(a, b):
    a_tokens = set(normalize_name(a).split())
    b_tokens = set(normalize_name(b).split())

    if not a_tokens or not b_tokens:
        return 0.0

    intersection = len(a_tokens & b_tokens)
    union = len(a_tokens | b_tokens)

    return intersection / union

In [74]:
pairs["name_token_overlap"] = pairs.apply(
    lambda row: token_overlap(
        row["s1_name"],
        row["matched_name"]
    ),
    axis=1
)

In [75]:
display(
    pairs[pairs["label"] == 1][[
        "s1_name",
        "matched_name",
        "name_tfidf_similarity",
        "name_token_overlap",
        "address_tfidf_similarity",
        "combined_score"
    ]]
    .sort_values("combined_score")
    .head(30)
)

,s1_name,matched_name,name_tfidf_similarity,name_token_overlap,address_tfidf_similarity,combined_score
2328,Ganpati & Co,Smt Gsanaptit and Co #56067,0.033782,0.166667,0.122392,0.056929
2534,Bharat Food Private Limited,भारत फूड प्राइवेट लिमिटेड,0.000000,0.000000,0.202666,0.060800
2337,Shakti Logistics Private Limited,शक्ति लॉजिस्टिक्स प्राइवेट लिमिटेड,0.000000,0.000000,0.213859,0.064158
32,Lakshmi Consultants Private Limited,लक्ष्मी कंसल्टेंट्स प्राइवेट लिमिटेड,0.000000,0.000000,0.216350,0.064905
2963,Shivam Builders,శివం బిల్డర్స్,0.000000,0.000000,0.241097,0.072329
876,Bharat Foundation Private Limited,भारत फाउंडेशन प्राइवेट लिमिटेड,0.000000,0.000000,0.249074,0.074722
1308,Great Surya Consulting Private Limited,ગ્રેટ સૂર્ય કન્સલ્ટિંગ પ્રાઇવેટ લિમિટેડ,0.000000,0.000000,0.263428,0.079028
937,Urban Food Private Limited,అర్బన్ ఫుడ్ ప్రైవేట్ లిమిటెడ్,0.000000,0.000000,0.267161,0.080148
479,Anderson Floating,Jaxxyl0,0.000000,0.000000,0.279722,0.083917
437,Pramod College Private Limited,Dr Zephsyn,0.000000,0.000000,0.320480,0.096144
2264,Fortune Finance Private Limited,फॉर्च्यून फाइनेंस प्राइवेट लिमिटेड,0.000000,0.000000,0.330129,0.099039
1220,Sunrise Construction Private Limited,सनराइज कंस्ट्रक्शन प्राइवेट लिमिटेड,0.000000,0.000000,0.343736,0.103121
130,Tech Infotech Private Limited,టెక్ ఇన్ఫోటెక్ ప్రైవేట్ లిమిటెడ్,0.000000,0.000000,0.353389,0.106017
1168,Royal Engineering LLP,रॉयल इंजीनियरिंग एलएलपी,0.000000,0.000000,0.357629,0.107289
1359,Silver Engineering Private Limited,சில்வர் இன்ஜினியரிங் பிரைவேட் லிமிடெட்,0.000000,0.000000,0.357948,0.107384
2350,Swastik Management,स्वस्तिक मैनेजमेंट,0.000000,0.000000,0.360078,0.108023
22,Creative Projects Limited,क्रिएटिव प्रोजेक्ट्स लिमिटेड,0.000000,0.000000,0.361734,0.108520
2578,Star Infra Private Limited,സ്റ്റാർ ഇൻഫ്ര പ്രൈവറ്റ് ലിമിറ്റഡ്,0.000000,0.000000,0.362158,0.108647
131,Tech Infotech Private Limited,టెక్ ఇన్ఫోటెక్ ప్రైవేట్ లిమిటెడ్,0.000000,0.000000,0.363833,0.109150
2554,Vista Solutions Private Limited,Fayelyracira,0.000000,0.000000,0.365865,0.109759
448,Alpha Tech Private Limited,ఆల్ఫా టెక్ ప్రైవేట్ లిమిటెడ్,0.000000,0.000000,0.366865,0.110060
470,Smart Management Private Limited,ಸ್ಮಾರ್ಟ್ ಮ್ಯಾನೇಜ್‌ಮೆಂಟ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,0.000000,0.370274,0.111082
281,Bright Systems Private Limited,ಬ್ರೈಟ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,0.000000,0.378868,0.113660
494,Krishna Finance,कृष्ण फाइनेंस,0.000000,0.000000,0.388403,0.116521
493,Krishna Finance,कृष्णा फाइनेंस,0.000000,0.000000,0.388403,0.116521
398,Raj Global Limited,राज ग्लोबल लिमिटेड,0.000000,0.000000,0.392915,0.117875
280,Bright Systems Private Limited,ಬ್ರೈಟ್ ಸಿಸ್ಟಮ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,0.000000,0.000000,0.398071,0.119421
2421,Anand Engineering Private Limited,आनंद इंजीनियरिंग प्राइवेट लिमिटेड,0.000000,0.000000,0.402669,0.120801
96,Ss Construction Private Limited,एसएस कंस्ट्रक्शन प्राइवेट लिमिटेड,0.000000,0.000000,0.402812,0.120844
1191,My Foundation Private Limited,माय फाउंडेशन प्राइवेट लिमिटेड,0.000000,0.000000,0.403216,0.120965

In [76]:
print("TOKEN OVERLAP BY LABEL")

print(
    pairs.groupby("label")["name_token_overlap"].describe()
)

TOKEN OVERLAP BY LABEL
        count      mean       std  min  25%       50%  75%  max
label
0      1000.0  0.030983  0.075320  0.0  0.0  0.000000  0.0  0.5
1      3451.0  0.638990  0.334669  0.0  0.5  0.666667  1.0  1.0

In [77]:
print("Mean token overlap:")
print(
    pairs.groupby("label")["name_token_overlap"].mean()
)

Mean token overlap:
label
0    0.030983
1    0.638990
Name: name_token_overlap, dtype: float64

In [78]:
def extract_numbers(text):
    if pd.isna(text):
        return set()

    return set(re.findall(r'\d+', str(text)))

In [79]:
def number_overlap(a, b):
    a_nums = extract_numbers(a)
    b_nums = extract_numbers(b)

    if not a_nums or not b_nums:
        return 0.0

    return len(a_nums & b_nums) / len(a_nums | b_nums)

In [80]:
pairs["address_number_overlap"] = pairs.apply(
    lambda row: number_overlap(
        row["s1_address"],
        row["matched_address"]
    ),
    axis=1
)

In [81]:
pairs["name_number_overlap"] = pairs.apply(
    lambda row: number_overlap(
        row["s1_name"],
        row["matched_name"]
    ),
    axis=1
)

In [82]:
print(
    pairs.groupby("label")[
        ["name_number_overlap", "address_number_overlap"]
    ].describe()
)

      name_number_overlap                                               \
                    count      mean       std  min  25%  50%  75%  max
label
0                  1000.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
1                  3451.0  0.015599  0.123384  0.0  0.0  0.0  0.0  1.0

      address_number_overlap
                       count      mean       std  min       25%  50%  75%  max
label
0                     1000.0  0.007362  0.047029  0.0  0.000000  0.0  0.0  0.5
1                     3451.0  0.701482  0.406240  0.0  0.333333  1.0  1.0  1.0

In [83]:
## Candidate pool Genertion
hard_candidate_rows = []

rng = np.random.default_rng(42)

SAMPLE_PER_S1 = 500

for _, s1_row in s1_sample.iterrows():

    s1_id = s1_row["entity_id"]
    country = s1_row["country"]

    true_ids = true_matches.get(s1_id, set())

    # Pick either S2 or S3
    s2_group = s2_by_country.get(country)
    s3_group = s3_by_country.get(country)

    groups = []

    if s2_group is not None and len(s2_group) > 0:
        groups.append(s2_group)

    if s3_group is not None and len(s3_group) > 0:
        groups.append(s3_group)

    if not groups:
        continue

    # Randomly choose one source
    group = groups[rng.integers(len(groups))]

    # Sample candidates
    sample_size = min(SAMPLE_PER_S1, len(group))

    indices = rng.choice(
        len(group),
        size=sample_size,
        replace=False
    )

    sampled = group.iloc[indices]

    # Remove actual matches for THIS S1
    sampled = sampled[
        ~sampled["entity_id"].isin(true_ids)
    ]

    for _, candidate in sampled.iterrows():

        hard_candidate_rows.append({
            "s1_id": s1_id,
            "s1_name": s1_row["business_name"],
            "s1_address": s1_row["business_address"],
            "s1_country": country,

            "matched_id": candidate["entity_id"],
            "matched_name": candidate["business_name"],
            "matched_address": candidate["business_address"],
            "matched_country": candidate["country"]
        })

hard_candidates = pd.DataFrame(hard_candidate_rows)

print("Hard candidate pairs:", len(hard_candidates))

Hard candidate pairs: 500000

In [84]:
## Calculate name TF-IDF similarity
hard_candidates["s1_norm"] = (
    hard_candidates["s1_name"]
    .apply(normalize_name)
)

hard_candidates["matched_norm"] = (
    hard_candidates["matched_name"]
    .apply(normalize_name)
)

In [85]:
hc_s1_vec = vectorizer.transform(
    hard_candidates["s1_norm"]
)

hc_matched_vec = vectorizer.transform(
    hard_candidates["matched_norm"]
)

In [86]:
hard_candidates["name_similarity"] = (
    hc_s1_vec.multiply(hc_matched_vec)
    .sum(axis=1)
    .A1
)

In [87]:
## Step 3 — Pick the hardest negative for each S1
hard_negatives = (
    hard_candidates
    .sort_values(
        ["s1_id", "name_similarity"],
        ascending=[True, False]
    )
    .groupby("s1_id")
    .head(1)
    .copy()
)

In [88]:
print("Hard negatives:", len(hard_negatives))

Hard negatives: 1000

In [89]:
# Step 4 — Make sure they really are negatives
hard_negatives["is_true_match"] = hard_negatives.apply(
    lambda row:
        row["matched_id"] in true_matches.get(row["s1_id"], set()),
    axis=1
)

print(
    hard_negatives["is_true_match"].value_counts()
)

is_true_match
False    1000
Name: count, dtype: int64

In [90]:
# Step 5 — Inspect our hard negatives
display(
    hard_negatives[[
        "s1_name",
        "matched_name",
        "name_similarity",
        "s1_address",
        "matched_address"
    ]]
    .sort_values("name_similarity", ascending=False)
    .head(30)
)

,s1_name,matched_name,name_similarity,s1_address,matched_address
153117,Flint Inc.,Flint Inc.,1.000000,"3123 Broad Street, Richmond City, VA","11407 Lake Gables Drive, Richmond, Texas"
5339,Ss Technology Private Limited,गोल्डन Technology Private Limited,0.885002,"Shop No. 1164, Pvt No.2, First Floor Kucha Mahajani, Chandni Chowk, Delhi, Central Delhi, Delhi","B-##4, SIRSI, SHIV SAGAR, AJMER ROAD, JAIPUR, Rajasthan"
481127,Pediatric Dental Center LLC,Pediatric Dental Center Of,0.881318,"14302 Little Rocky Mountain Court, Fairfax County, VA","586. Knotwood Street, Green Valley, Arizona"
177665,My Foundation Private Limited,শিবম সূর্য Foundation Private Limited,0.869975,"Plot No-15A, New Township, Faridabad, Haryana","NEW TOWN SQUARE 2ND FLOOR RN 2C2 RAJARHAT, KOLKATA, HOWRAH, West Bengal"
340194,Swastik Management,Swastik Limited Private Management,0.841056,"Flat No. 1006, 10Th Floor Block C, Hig Flats, Sec 29, Rohini, Delhi, West Delhi, Delhi","Door No 3/63, Kannur, Ramanthali Grama Panchayat, Keralam"
218647,Perfect Finance Pvt Ltd,Perfect Finance LLP,0.839126,"C/O Munna Thakur, Ward No7, Ward No.-7, Ps-Malahi, Areraj, East Champaran, Bihar","Block C-431 P.no.b-347, Mahesh Nagar, Jaipur, NULL, राजस्थान"
211289,Mishra Services Public Limited,Shri AKSHRA SERVICES PUBLIC LIMITED,0.836686,"Office No.602, S.No.45/1 To 10/1, Pashankar Auto, Pune City, Pune, Maharashtra","HN 774 17, DAS LANE, 3RD FLOOR, KOLKATA, KOLKATA, West Bengal"
447580,Sepl Institute of Technology,Impex Institute of Technology,0.819078,"B-45 Haryhur Society Village Khambhat Taluka Khambhat District Anand, Khambhat, Anand, Gujarat","BLOCK D-521 FLAT- H 1, KH NO. 56/14, U/GROUND FLBOR, SECTOR-19, VILLAGE AMBERHAI, NEW DELHI, Delhi"
38050,Meridian,Meridian Co,0.809004,"9 Pitts Street, Natick, MA","319 Hillsdale Estates Ln, Hillsdale, Tennessee"
15266,Bhopal Consultancy Limited,Private Al Consultancy Limited,0.805091,"39, Old Ashoka Garden, Near Church, Raisen Road, Bhopal, Madhya Pradesh","RAJARAM PATIL NAGAR, WAGHOLI, Maharashtra"
485525,Wealthy Solutions Private Limited,Jay Solutions Private Limited,0.787108,"Unit No. 703, 704, Amba Tower, Plot No.2, Community Centre, D.C Chowk, Sector-9, Delhi, North West Delhi, Delhi","D/102, First Floor, Wing 'B' Balaji Garden, Indralok Phase Viii, Bhay, Ander East, Thane, MH"
43298,KS Enterprises Private Limited,agarsons enterprises private limited,0.784418,"Plot 1412, Chanakyapuri, Sainik Colony Pushpa Raj Sumitra Sadan Gola Road, Patna, Bihar","P. No. 016, South West Delhi, DL"
123824,New Delhi India Pvt Ltd,Delhi India Pvt,0.784291,"Plot No-15, S/F, Kh No 16/3, Bajaj Enclave, New Delhi, South West Delhi, Delhi","505, Nikita Tower- 2, C-1/4, Azadpur Commercial Complex, Delhi, North Delhi, DL"
130540,Indo Investment Private Limited,ALL Investment Private Limited,0.776695,"H. No. 56, Front Portion, Ground Floor Block 7, South Patel Nagar, Delhi, West Delhi, Delhi","No 327, Room No.104, I Floor, Sunrise Mansion, Dr. Rajkumar Road, 6Th Bclock Circle, Raj, Bengaluru Urban, Bangalore, KA"
56185,Tech Energy Private Limited,BIG ENERGY PRIVATE LIMITED,0.775511,"No.310, Andanappa Circle, Thotadaguddahalli, Bangalore North, Bangalore, Karnataka","Door No 21, Chennai, Madras, TN"
342393,Ear Nose & Throat Medicine LLC,Ear Nose & Throat Care Inc,0.773041,"2500 Melbrook Drive, Kankakee, IL","14490 Southpointe Drive, Unit APT 7304, Folsom, California"
446186,All Marketing Private Limited,RAJ MARKETING PRIVATE LIMITED,0.772610,"302 2Nd Floor, Bhera Enclave, Paschim Vihar, New Delhi, West Delhi, Delhi",NaN
244706,Pediatric Dental Group,Pediatric Dental Group Of Services,0.772321,"451 Adams Avenue, Lebanon, TN","18418 Cr 2, Forest, Ohio"
309953,Laxmi International Pvt Ltd,Laxmi International Pharmacy Pvt Ltd,0.771944,"1322/89 Hemkunt Chamber 13Th Floor Nehru Place, Delhi, New Delhi, Delhi","C-232, Second Floor, Alpha 1, Krishna Apra Plaza, Greater Noida, Gautam Buddha Nagar, Noida, UP"
400803,Ear Nose & Throat Supreme Care PC,EAR NOSE & THROAT CÁRE LLC,0.771780,"37 Commonwealth Avenue, Unit 4RR, Boston, MA","2610 Hardwood Ct, Louisville, Kentucky"
113269,Sun Infrastructure Limited,UU Infrastructure Limited Private,0.767574,"Spaze It Park, Tower B3, 4Th Floor, Unit No- 442-4, Gurgaon, Haryana","FLAT NO. C-520 , A BLOCK, SHANTASRIRAM CHALET MEADOWS DR NO. 1-4-888/1, 2, B, 4, 5, BAKARAM, MUSHE, ERABAD, HYDERABAD, Telangana"
488827,Eastern Constructions Private Limited,United Eastern Constructions Pvt Ltd.,0.765471,"Madurai, 36A/12, Tamil Nadu, Khan Palayam, 4Th Street, Madurai North","18 A NEW UNIQUE IND ESTATEDR R P RD MULUND (W), MUMBAI, महाराष्ट्र"
395718,Shantaram Institute of Technology,vikram institute of technology limited,0.764295,"D-38/A, Ashok Marg C-Scheme, Near Ahinsa Circle, Rajasthan, Jaipur","C/O MR MANOHAR A MARODKAR MAHADEO NAGAR, AMT, AMRAVATI, Maharashtra"
111917,Jai Trading Private Limited,>> jade trading private limited,0.755089,"81/D, R.K.Chatterjee Road Ground Floor, Kolkata, Howrah, West Bengal","45 VELALER COLONY 3RD STREET TIRUCHENGODE (TK), NAMAKKAL, NAMAKAL, Tamil Nadu"
100246,Apex Enterprises Private Limited,Tech Enterprises Private (Limited),0.744664,"C/O Prashant Rathod, Balaji Nagar Mehkar, Mehkar, Buldhana, Maharashtra","H.no 78 Nirmal Apartments Chitaley, Marg Dhantoli Nagpur, Nagpur, MH"
224332,Hari Marketing LLP,Ram Marketing-LLP,0.744327,"808, Pearl Best Heights-I, Nsp, Pitampura, Delhi, North West Delhi, Delhi","95A Balaram Dey Street, Kolkata Region, Calcutta, WB"
417364,Legacy Logistics Enterprises Inc,Legacy Logistics,0.743197,"1312 O Avenue, Unit 3, Anacortes, WA","Ohio, Powell, 2543 Racher Dr"
137607,Urology Physicians LLC,Dermatology Physicians Co,0.741708,"1689 Parco Avenue, Ontario, CA","27 1/2 Rivers Edge Dr, Tarrytown, New York"
17588,Tech Infotech Private Limited,EAST ÍNFOTECH PRIVATE,0.738364,"Sri Siddi Vinayaka Apartm, Telangana, Karimnagar, Karim Nagar, 8-6-375/3/8","Madhya Pradesh, 1.AASHISH VIHAR EXTN. NEAR BANGALI CHAURAHA, INDORE"
448008,Brady Dental Associates,Dental Associates Corp,0.737017,"12365 Ensley Drive, Fishers, IN","13936. 812, DEL VALLE, TX"

In [91]:
# Prepare hard negatives
hard_negatives["s1_norm"] = hard_negatives["s1_name"].apply(normalize_name)
hard_negatives["matched_norm"] = hard_negatives["matched_name"].apply(normalize_name)

hard_negatives["s1_core"] = hard_negatives["s1_name"].apply(extract_core_name)
hard_negatives["matched_core"] = hard_negatives["matched_name"].apply(extract_core_name)

hard_negatives["s1_address_norm"] = hard_negatives["s1_address"].apply(normalize_address)
hard_negatives["matched_address_norm"] = hard_negatives["matched_address"].apply(normalize_address)

In [92]:
# TF-IDF similarities
s1_vec_h = vectorizer.transform(hard_negatives["s1_norm"].fillna(""))
matched_vec_h = vectorizer.transform(hard_negatives["matched_norm"].fillna(""))

s1_core_vec_h = core_vectorizer.transform(
    hard_negatives["s1_core"].fillna("")
)

matched_core_vec_h = core_vectorizer.transform(
    hard_negatives["matched_core"].fillna("")
)

s1_addr_vec_h = address_vectorizer.transform(
    hard_negatives["s1_address_norm"].fillna("")
)

matched_addr_vec_h = address_vectorizer.transform(
    hard_negatives["matched_address_norm"].fillna("")
)

In [93]:
hard_negatives["name_tfidf_similarity"] = (
    s1_vec_h.multiply(matched_vec_h).sum(axis=1).A1
)

hard_negatives["core_tfidf_similarity"] = (
    s1_core_vec_h.multiply(matched_core_vec_h).sum(axis=1).A1
)

hard_negatives["address_tfidf_similarity"] = (
    s1_addr_vec_h.multiply(matched_addr_vec_h).sum(axis=1).A1
)

In [94]:
# Token overlap
hard_negatives["name_token_overlap"] = hard_negatives.apply(
    lambda row: token_overlap(
        row["s1_name"],
        row["matched_name"]
    ),
    axis=1
)

In [95]:
# Number features
hard_negatives["name_number_overlap"] = hard_negatives.apply(
    lambda row: number_overlap(
        row["s1_name"],
        row["matched_name"]
    ),
    axis=1
)

hard_negatives["address_number_overlap"] = hard_negatives.apply(
    lambda row: number_overlap(
        row["s1_address"],
        row["matched_address"]
    ),
    axis=1
)

In [96]:
# Country match
hard_negatives["country_match"] = (
    hard_negatives["s1_country"] ==
    hard_negatives["matched_country"]
).astype(int)

In [97]:
# Label them
hard_negatives["label"] = 0

In [98]:
hard_negatives[
    [
        "s1_name",
        "matched_name",
        "name_tfidf_similarity",
        "core_tfidf_similarity",
        "address_tfidf_similarity",
        "name_token_overlap",
        "address_number_overlap",
        "label"
    ]
].sort_values(
    "name_tfidf_similarity",
    ascending=False
).head(20)

,s1_name,matched_name,name_tfidf_similarity,core_tfidf_similarity,address_tfidf_similarity,name_token_overlap,address_number_overlap,label
153117,Flint Inc.,Flint Inc.,1.000000,1.000000,0.313853,1.000000,0.0,0
5339,Ss Technology Private Limited,गोल्डन Technology Private Limited,0.885002,0.803691,0.042336,0.750000,0.0,0
481127,Pediatric Dental Center LLC,Pediatric Dental Center Of,0.881318,0.905667,0.013037,0.600000,0.0,0
177665,My Foundation Private Limited,শিবম সূর্য Foundation Private Limited,0.869975,0.787345,0.089018,0.750000,0.0,0
340194,Swastik Management,Swastik Limited Private Management,0.841056,0.768695,0.025914,0.500000,0.0,0
218647,Perfect Finance Pvt Ltd,Perfect Finance LLP,0.839126,1.000000,0.031993,0.400000,0.0,0
211289,Mishra Services Public Limited,Shri AKSHRA SERVICES PUBLIC LIMITED,0.836686,0.809090,0.017919,0.500000,0.0,0
447580,Sepl Institute of Technology,Impex Institute of Technology,0.819078,0.810237,0.089946,0.600000,0.0,0
38050,Meridian,Meridian Co,0.809004,1.000000,0.011513,0.500000,0.0,0
15266,Bhopal Consultancy Limited,Private Al Consultancy Limited,0.805091,0.690634,0.040908,0.400000,0.0,0
485525,Wealthy Solutions Private Limited,Jay Solutions Private Limited,0.787108,0.668261,0.027922,0.600000,0.0,0
43298,KS Enterprises Private Limited,agarsons enterprises private limited,0.784418,0.683335,0.004563,0.600000,0.0,0
123824,New Delhi India Pvt Ltd,Delhi India Pvt,0.784291,0.647009,0.219017,0.600000,0.0,0
130540,Indo Investment Private Limited,ALL Investment Private Limited,0.776695,0.648948,0.084350,0.600000,0.0,0
56185,Tech Energy Private Limited,BIG ENERGY PRIVATE LIMITED,0.775511,0.582666,0.020393,0.600000,0.0,0
342393,Ear Nose & Throat Medicine LLC,Ear Nose & Throat Care Inc,0.773041,0.832230,0.054752,0.428571,0.0,0
446186,All Marketing Private Limited,RAJ MARKETING PRIVATE LIMITED,0.772610,0.661144,0.000000,0.600000,0.0,0
244706,Pediatric Dental Group,Pediatric Dental Group Of Services,0.772321,0.772267,0.000000,0.600000,0.0,0
309953,Laxmi International Pvt Ltd,Laxmi International Pharmacy Pvt Ltd,0.771944,0.767321,0.054300,0.800000,0.0,0
400803,Ear Nose & Throat Supreme Care PC,EAR NOSE & THROAT CÁRE LLC,0.771780,0.778449,0.004941,0.571429,0.0,0

High name similarity + low address similarity can still be a negative.

Ready for classification

In [99]:
# Step 1 — Combine your datasets
training_data = pd.concat(
    [pairs, hard_negatives],
    ignore_index=True
)

print(training_data.shape)
print(training_data["label"].value_counts())

(5451, 25)
label
1    3451
0    2000
Name: count, dtype: int64

In [100]:
# Step 2 — Select our features
features = [
    "name_tfidf_similarity",
    "core_tfidf_similarity",
    "address_tfidf_similarity",
    "name_token_overlap",
    "name_number_overlap",
    "address_number_overlap",
    "country_match"
]

In [101]:
X = training_data[features]
y = training_data["label"]

print(X.shape)
print(X.isna().sum())

(5451, 7)
name_tfidf_similarity       0
core_tfidf_similarity       0
address_tfidf_similarity    0
name_token_overlap          0
name_number_overlap         0
address_number_overlap      0
country_match               0
dtype: int64

In [102]:
from sklearn.model_selection import GroupShuffleSplit

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.2,
    random_state=42
)

train_idx, val_idx = next(
    splitter.split(
        training_data,
        training_data["label"],
        groups=training_data["s1_id"]
    )
)

train_data = training_data.iloc[train_idx]
val_data = training_data.iloc[val_idx]

print("Train:", train_data.shape)
print("Validation:", val_data.shape)

Train: (4346, 25)
Validation: (1105, 25)

In [103]:
X_train = train_data[features]
y_train = train_data["label"]

X_val = val_data[features]
y_val = val_data["label"]

In [104]:
print(training_data.shape)
print(training_data["label"].value_counts())

print(train_data.shape)
print(val_data.shape)

(5451, 25)
label
1    3451
0    2000
Name: count, dtype: int64
(4346, 25)
(1105, 25)

In [105]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [106]:
val_probs = model.predict_proba(X_val)[:, 1]

In [107]:
from sklearn.metrics import classification_report

val_pred = (val_probs >= 0.5).astype(int)

print(classification_report(y_val, val_pred))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97       400
           1       1.00      0.97      0.98       705

    accuracy                           0.98      1105
   macro avg       0.97      0.98      0.98      1105
weighted avg       0.98      0.98      0.98      1105

In [108]:
from sklearn.metrics import fbeta_score

f05 = fbeta_score(
    y_val,
    val_pred,
    beta=0.5
)

print("F0.5:", f05)

F0.5: 0.9910430511412887

In [109]:
from sklearn.metrics import precision_score, recall_score

In [110]:
import numpy as np

thresholds = np.arange(0.1, 0.96, 0.01)

results = []

for threshold in thresholds:
    pred = (val_probs >= threshold).astype(int)

    precision = precision_score(y_val, pred, zero_division=0)
    recall = recall_score(y_val, pred, zero_division=0)
    f05 = fbeta_score(
        y_val,
        pred,
        beta=0.5,
        zero_division=0
    )

    results.append(
        (threshold, precision, recall, f05)
    )

In [111]:
results_df = pd.DataFrame(
    results,
    columns=["threshold", "precision", "recall", "f05"]
)

display(
    results_df.sort_values(
        "f05",
        ascending=False
    ).head(10)
)

    threshold  precision    recall       f05
29       0.39   0.995690  0.982979  0.993121
26       0.36   0.995690  0.982979  0.993121
27       0.37   0.995690  0.982979  0.993121
28       0.38   0.995690  0.982979  0.993121
25       0.35   0.995690  0.982979  0.993121
19       0.29   0.994278  0.985816  0.992574
32       0.42   0.995677  0.980142  0.992531
31       0.41   0.995677  0.980142  0.992531
30       0.40   0.995677  0.980142  0.992531
56       0.66   0.998538  0.968794  0.992444

In [112]:
best_threshold = 0.39

val_results = val_data.copy()
val_results["probability"] = val_probs
val_results["prediction"] = (
    val_probs >= best_threshold
).astype(int)

false_positives = val_results[
    (val_results["label"] == 0) &
    (val_results["prediction"] == 1)
]

false_negatives = val_results[
    (val_results["label"] == 1) &
    (val_results["prediction"] == 0)
]

print("False positives:", len(false_positives))
print("False negatives:", len(false_negatives))

False positives: 3
False negatives: 12

In [113]:
display(
    false_positives[
        [
            "s1_id",
            "s1_name",
            "matched_id",
            "matched_name",
            "name_tfidf_similarity",
            "core_tfidf_similarity",
            "address_tfidf_similarity",
            "name_token_overlap",
            "address_number_overlap"
        ]
    ].head(20)
)

,s1_id,s1_name,matched_id,matched_name,name_tfidf_similarity,core_tfidf_similarity,address_tfidf_similarity,name_token_overlap,address_number_overlap
4707,S1-317776099,Flint Inc.,S3-781770443,Flint Inc.,1.000000,1.000000,0.313853,1.00,0.0
5296,S1-862712171,My Foundation Private Limited,S2-408259952,শিবম সূর্য Foundation Private Limited,0.869975,0.787345,0.089018,0.75,0.0
5436,S1-983540069,Ss Technology Private Limited,S2-711137109,गोल्डन Technology Private Limited,0.885002,0.803691,0.042336,0.75,0.0

In [114]:
display(
    false_negatives[
        [
            "s1_id",
            "s1_name",
            "matched_id",
            "matched_name",
            "name_tfidf_similarity",
            "core_tfidf_similarity",
            "address_tfidf_similarity",
            "name_token_overlap",
            "address_number_overlap"
        ]
    ].head(20)
)

,s1_id,s1_name,matched_id,matched_name,name_tfidf_similarity,core_tfidf_similarity,address_tfidf_similarity,name_token_overlap,address_number_overlap
81,S1-369198632,Federman Chimera Associates,S3-871488044,Federman Center Associates,0.669916,0.669020,0.000000,0.50,0.0
378,S1-281408668,Carpenters Union Local No 961,S2-23692283,Carpenters Union Local,0.787160,0.794878,0.000000,0.60,0.0
459,S1-153594731,Wilkinson Meshflow LLC,S2-209658522,Wilkinson Meshflow L.L.C.,0.865365,0.806475,0.000000,0.40,0.0
661,S1-952865119,Hari Care Private Limited,S3-17493899,Hari Care,0.700905,1.000000,0.000000,0.50,0.0
888,S1-621208988,Koch Charter School,S2-682448909,Koch Charter Shfol,0.687403,0.691633,0.000000,0.50,0.0
930,S1-690151152,Masco Foundation,S2-228559678,Shri Masco Service,0.241418,0.209334,0.000000,0.25,0.0
1227,S1-68170645,Peyton's Mountain Hospitality,S3-905748682,Peyton'S Mountain #78918,0.685252,0.685002,0.000000,0.60,0.0
1308,S1-373896077,Great Surya Consulting Private Limited,S3-105954325,ગ્રેટ સૂર્ય કન્સલ્ટિંગ પ્રાઇવેટ લિમિટેડ,0.000000,0.000000,0.263428,0.00,0.0
2143,S1-810734839,"Ronet Clear Texas, L.L.C.",S3-244783304,"Ronet Clear Texas, LLC",0.872405,0.827475,0.000000,0.50,0.0
2271,S1-39113532,EVL Shipping Private Limited,S3-398898051,EVL 5hipping Private Limited,0.706240,0.500732,0.000000,0.60,0.0
2743,S1-421140629,Sunderland Baptist Association,S3-125287699,Sunderland Baptist Assocoiogiron,0.822024,0.821196,0.000000,0.50,0.0
3096,S1-491138472,Tejiya Developers Center,S3-43710305,Tejiya Center Partners,0.375908,0.371992,0.000000,0.50,0.0

Ready for testing

In [ ]:
test_source2 = pd.read_csv(
    "test_source2.tsv",
    sep="\t"
)

test_source3 = pd.read_csv(
    "test_source3.tsv",
    sep="\t"
)

In [ ]:
test_source1 = pd.read_csv(
    "test_source1.tsv",
    sep="\t"
)