Data preprocessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
s1 = pd.read_csv('train_source1.tsv',sep='\t')

In [3]:
s2 = pd.read_csv('train_source2.tsv',sep='\t')

In [4]:
s3 = pd.read_csv('train_source3.tsv',sep='\t')

In [5]:
truth = pd.read_csv('train_ground_truth.tsv',sep='\t')

In [6]:
print("S1:", s1.shape)
print("S2:", s2.shape)
print("S3:", s3.shape)
print("Truth:", truth.shape)

print(s1.head())
print(s2.head())
print(s3.head())
print(truth.head())

S1: (2206821, 4)
S2: (5034616, 4)
S3: (5285603, 4)
Truth: (2206821, 2)
      entity_id            business_name  \
0  S1-925783039      Orelee's Barbershop
1  S1-773889195              Prime Money
2  S1-377745466            B+ Retail Inc
3  S1-133037285            Christ Chapel
4  S1-755362802  Prabhav Business Center

                                    business_address country
0             1795 Westchester Drive, High Point, NC      US
1                    17560 Ellis Road, Tahlequah, OK      US
2                1712 Montebello Avenue, Phoenix, AZ      US
3  2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD      US
4  797, Lake Town Block A, Kolkata, Howrah, West ...   India
      entity_id                    business_name  \
0  S2-166376419  राम मार्केटिंग प्राइवेट लिमिटेड
1  S2-764573417     -- Holloway Peak Inc Seafood
2  S2-639257739         आदित्य प्रॉपर्टीज एलएलपी
3  S2-163963287                       Summit Inc
4   S2-49942811     Delta Tetlecommunication Inc

                                   business_address country
0      KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi   India
1                         105 ELM ST, MORGANTON, NC      US
2  G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh   India
3             GREENSBORO, NC, 19 1/2 STARDUST TRAIL      US
4                   914 PIERPONT AVE, CLEVELAND, OH      US
      entity_id                                business_name  \
0  S3-202863386                           wilfordhancock.com
1  S3-859268022  International South Consultants Private Ltd
2   S3-22467283                  LLC Moncada Léarning Center
3  S3-671162755                               Moyna's Coffee
4  S3-960981775                 Pvt. EFS Print Ventures Ltd.

                                    business_address country
0                        Mack Rd, Haltom City, Texas      US
1                                                NaN   India
2                    5780 Fawn Ct, Fort Worth, Texas      US
3       1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio      US
4  Door No 183, 41St Cross, 22Nd Main 9Th Block J...   India
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [7]:
print(s1.columns)
print(s2.columns)
print(s3.columns)
print(truth.columns)

Index(['entity_id', 'business_name', 'business_address', 'country'], dtype='object')
Index(['entity_id', 'business_name', 'business_address', 'country'], dtype='object')
Index(['entity_id', 'business_name', 'business_address', 'country'], dtype='object')
Index(['source1_entity_id', 'matched_entity_ids'], dtype='object')

In [8]:
pd.set_option('display.max_colwidth',200)

print(
    s1[["entity_id", "business_name", "country"]].head(30).to_string(index=False)
)

   entity_id                            business_name country
S1-925783039                      Orelee's Barbershop      US
S1-773889195                              Prime Money      US
S1-377745466                            B+ Retail Inc      US
S1-133037285                            Christ Chapel      US
S1-755362802                  Prabhav Business Center   India
S1-851869949               Custom Wealth Services LLC      US
S1-785847572 Consulting Nyasa Nursing Private Limited   India
 S1-27541239                        Nexus Anchor Rain      US
S1-629417405                        Moore Bitwise Inc      US
 S1-22305073               Dermatology Green Medicine      US
S1-504790211                       Crystal Lending PC      US
S1-564729135               Dream Construction Limited   India
S1-236312382                      Kelly Advisory, Inc      US
S1-865131206                                   Helios      US
S1-626914593                   Unified Choice Dynamix      US
S1-765734254               Health Fellowship Partners      US
 S1-82053739         Smart Healthcare Private Limited   India
S1-309349399                   Callicoat & Dailey Inc      US
S1-221443075                            Iris Advisors   India
S1-341506266        Secunderabad Park Private Limited   India
S1-990319941                           Holy Synagogue      US
S1-597762257          Green Logistics Private Limited   India
S1-661315962                          Scott Eagle Inc      US
S1-716574008             Rajani Enterprises of Kannur   India
S1-985038901  Schaefer, Michael and Silver Associates      US
S1-404435514                  Colline Molitor Sea LLC      US
S1-252242682                 Aggie E. Nagle, L.C.S.W.      US
S1-981440385                     Angad Multitrade Ltd   India
S1-883973644                     Global Hovnanian LLC      US
 S1-17666546        Pacific Learning Laboratories LLC      US

In [9]:
print(
    s2[["entity_id", "business_name", "country"]].head(30).to_string(index=False)
)

   entity_id                                                            business_name country
S2-166376419                                          राम मार्केटिंग प्राइवेट लिमिटेड   India
S2-764573417                                             -- Holloway Peak Inc Seafood      US
S2-639257739                                                 आदित्य प्रॉपर्टीज एलएलपी   India
S2-163963287                                                               Summit Inc      US
 S2-49942811                                             Delta Tetlecommunication Inc      US
S2-138046867                                                           Lee and Lawson      US
S2-584977605 SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPORATION | www.shivshakti.com   India
S2-277444929                                               Shree Infracon Private Ltd   India
S2-721031885                                             Chavira Platinum Chimera LLC      US
S2-508602797                                 FOUNDATION EXCEL AGENCY PRIVATE  LIMITED   India
 S2-69394310                                                         heassociates.com      US
S2-615967906                                         सन कंस्ट्रक्शंस प्राइवेट लिमिटेड   India
S2-684635925                               Global Developers Medicals Private Limited   India
S2-868087865                                             ASSET BUILDING COALITION LLC      US
S2-795141272                                        Olszewski Holding Company LLC LLC      US
S2-414418413                                                         CANDY'S-SERVICES      US
S2-566688803                                                  रियल मॉडर्न फूड लिमिटेड   India
S2-634015823                                             Crestline Crestline Clean LP      US
S2-378707035                                                                     Nion      US
S2-953098128                                             Keystone Odyssey Odyssey LLC      US
S2-526991413                                                  Jones Royal  Bancshares      US
S2-879667609                                        குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்   India
S2-202057528                                                          Altitude Retail   India
S2-763108962                                                 Core Welfare Society LLP   India
S2-415733261                                                    Sweet Barbershop (Co)      US
S2-294835210                                                            COBALT  (LLC)      US
S2-944853638                                          Piedmont Complete Chile  L.L.C.      US
S2-235039028                                                Empire School of Medicine      US
S2-783158461                                                   Animal Welfare Nétwork      US
S2-669879950                                               Hail, Harris & Roberts Inc      US

In [10]:
print(
    s3[["entity_id", "business_name", "country"]].head(30).to_string(index=False)
)

   entity_id                               business_name country
S3-202863386                          wilfordhancock.com      US
S3-859268022 International South Consultants Private Ltd   India
 S3-22467283                 LLC Moncada Léarning Center      US
S3-671162755                              Moyna's Coffee      US
S3-960981775                Pvt. EFS Print Ventures Ltd.   India
S3-578159284              LLC Hernandez Colonial Redwood      US
S3-121412624               Classic Equity Partners Group      US
S3-249416830              Ectolumdrex dba X+ Madison Inc      US
S3-107644605                     Animal Hanisch Hospirlg      US
S3-160217003                               Gomez Optimal      US
S3-504183980            The Rapid  Learning Alliance LLC      US
 S3-53737228                  Indian Care Public Limited   India
 S3-16693061                                       Béque      US
S3-331103166                           #centraleducation      US
 S3-45067784         அரிஹந்த் Foundation Private Limited   India
S3-118652570                         Wildlife Guild  LLC      US
 S3-90100170                          Cinder Charlton-PC      US
S3-476778426                              ZRO Trinity Co      US
S3-128062172           Bajaj Foundation  Private Limited   India
S3-171901473                           Estell's Creative      US
S3-973629095                          Center 5uperior Co      US
S3-554084947                            Palace Vidyalaya   India
S3-315861895                              Global Applied      US
S3-326049086                Integrated  Business Systems      US
S3-181819854 Cardiology Heartland Cáre Associates #98825      US
S3-776815069                   Sai  Surgical (India) Ltd   India
S3-230314480 MW Management Private  Limited - 2067865001   India
S3-807500071                        FERRERO FERRERO DUKE      US
S3-878295053           Chinglepet Private Limited Center   India
S3-725749046                      Modern Center Brothers   India

In [11]:
print(truth.head(20).to_string(index=False))

source1_entity_id                                                                        matched_entity_ids
        S1-965667                           S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
      S1-55344266                                       S2-249013014,S2-197070651,S3-478195123,S3-384364074
     S1-343815751                                                    S2-790675320,S2-479876582,S3-878454467
     S1-656753428                                                     S2-153058913,S2-24659151,S3-679606215
     S1-102811957             S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785
      S1-18727616                                       S2-755677256,S3-187831601,S3-641489370,S3-476250621
     S1-318373630                                                                 S2-660036492,S3-804600254
      S1-86989137                                                                 S3-274817120,S3-312496301
      S1-29845983                                                                 S2-648035184,S3-588502663
     S1-789009573                                                     S2-383871912,S3-74481402,S3-576451439
     S1-730934468                                                                 S2-356983532,S3-352439310
       S1-7293388                                         S2-7028416,S2-442723188,S2-157073701,S3-523120965
     S1-546142636             S2-487600131,S2-582477216,S2-392804085,S3-200008747,S3-729771680,S3-249331830
     S1-274126313              S2-736616474,S2-680265918,S2-51486805,S3-925631694,S3-461175723,S3-850112871
     S1-145361722                                                     S2-120366543,S2-939389287,S3-96572514
     S1-503957000 S2-994658326,S2-235117490,S2-353308450,S2-173295926,S3-858763214,S3-33665521,S3-555791452
     S1-692000596                                                                 S2-580419223,S3-164220452
     S1-561341312                                                                 S2-483615364,S3-619529814
     S1-777597828                                                                 S2-836452886,S3-413669121
     S1-282467635                                                                 S2-938895481,S3-138350041

In [12]:
s1_lookup = s1.set_index('entity_id')
s2_lookup = s2.set_index('entity_id')
s3_lookup = s3.set_index('entity_id')


def show_matches(s1_id):

    print('=' * 100)

    s1_row = s1_lookup.loc[s1_id]

    # S1 record
    print("S1")
    print("ID      :", s1_id)
    print("NAME    :", s1_row["business_name"])
    print("ADDRESS :", s1_row["business_address"])
    print("COUNTRY :", s1_row["country"])

    # Ground truth
    truth_row = truth[truth["source1_entity_id"] == s1_id]

    matched_ids = truth_row.iloc[0]["matched_entity_ids"].split(",")

    print("\nTRUE MATCHES:")

    for entity_id in matched_ids:

        entity_id = entity_id.strip()

        if entity_id.startswith("S2-"):
            row = s2_lookup.loc[entity_id]

        elif entity_id.startswith("S3-"):
            row = s3_lookup.loc[entity_id]

        print("\n", entity_id)
        print("NAME    :", row["business_name"])
        print("ADDRESS :", row["business_address"])
        print("COUNTRY :", row["country"])

In [13]:
show_matches("S1-55344266")

====================================================================================================
S1
ID      : S1-55344266
NAME    : Raj Investments LLP
ADDRESS : 6(29), C.I.T. Colony, 2Nd Main Road Mylapore, Chennai, Tamil Nadu
COUNTRY : India

TRUE MATCHES:

 S2-249013014
NAME    : ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி
ADDRESS : 6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, CHENNAI, Tamil Nadu
COUNTRY : India

 S2-197070651
NAME    : Raj Investments LLP
ADDRESS : 6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, CHENNAI, Tamil Nadu
COUNTRY : India

 S3-478195123
NAME    : Raj Investments எல்எல்பி
ADDRESS : 6(29), C.i.t. Colony, 2Nd Main Road Mylapore, Chennai, TN
COUNTRY : India

 S3-384364074
NAME    : ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி
ADDRESS : 6(29), C.i.t. Colony, 2Nd Main Road Mylapore, Chennai, தமிழ்நாடு
COUNTRY : India

In [14]:
sample_truth = truth.sample(10000, random_state=42)

In [15]:
## creating true pairs
pairs = []

for _, row in sample_truth.iterrows():

    s1_id = row["source1_entity_id"]
    matched_ids = str(row["matched_entity_ids"]).split(",")

    s1_row = s1_lookup.loc[s1_id]

    for entity_id in matched_ids:

        entity_id = entity_id.strip()

        if entity_id.startswith("S2-"):
            matched_row = s2_lookup.loc[entity_id]

        elif entity_id.startswith("S3-"):
            matched_row = s3_lookup.loc[entity_id]

        else:
            continue

        pairs.append({
            "s1_name": s1_row["business_name"],
            "matched_name": matched_row["business_name"],
            "s1_address": s1_row["business_address"],
            "matched_address": matched_row["business_address"],
        })

sample_pairs = pd.DataFrame(pairs)

In [16]:
sample_pairs.head(20)

,s1_name,matched_name,s1_address,matched_address
0,"FQ Social, Inc","FQ Social, Inc.","1212 Old Rte 34, Sandwich, IL","1212 OLD RTE 34, SANDWICH, IL"
1,"FQ Social, Inc","FQ Social, #42836","1212 Old Rte 34, Sandwich, IL","1212 OLD RTE 34, SANDWICH, IL"
2,"FQ Social, Inc","FQ Social, Ínc","1212 Old Rte 34, Sandwich, IL","1212 Old Rte 34, Sandwich, Illinois"
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc","1212 Old Rte 34, Sandwich, IL","1212 Old Rte 34, Sandwich, IL"
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,"15 16 Indrapuri Madhubancolony Karvenagar, Pune, Maharashtra","H.NO B3/15 16 INDRAPURI MADHUBANCOLONY KARVENAGAR, PUNE, POONA, महाराष्ट्र"
5,Innovative Consultants,Innovative Consultants,"15 16 Indrapuri Madhubancolony Karvenagar, Pune, Maharashtra",NaN
6,Innovative Consultants,Innovative Consultants,"15 16 Indrapuri Madhubancolony Karvenagar, Pune, Maharashtra","#B3/15 16 INDRAPURI MADHUBANCOLONY KARVENAGAR, PUNE, Maharashtra"
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,"9-14, Hari Krishna Building, 2Nd Fl Dilsukhnagar, Hyderabad, Telangana","G-9-14, HARI KRISHNA BUILDING, 2ND FL DILSUKHNAGAR, HYDERABAD, తెలంగాణ"
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,"9-14, Hari Krishna Building, 2Nd Fl Dilsukhnagar, Hyderabad, Telangana","9-14, Hari Krishna Building, 2Nd Fl Dilsukhnagar, Hyderabad, Andhra Pradesh"
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]","Hampton City, VA, 234 Summit Court","SUMMIT CT, HAAMPTON, VA"
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc","Hampton City, VA, 234 Summit Court","234-236 SUMMIT COURT, HAAMPTON, VA"
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods","Hampton City, VA, 234 Summit Court","34 Summit Ct, Hampton, Virginia"
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,"4484 Westwood Drive, West Des Moines, IA","IA, WEST DES MOINES, 4484D WESTWOOD DRIVE"
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,"4484 Westwood Drive, West Des Moines, IA","4484- Westwood Drive, West Des Moines, Iowa"
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center","4484 Westwood Drive, West Des Moines, IA","4484- Westwood Dr, West Des Moines, Iowa"
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,"Vill-Belpukur, P.O. Balarampur, Berhampore, Murshidabad, West Bengal","West Bengal, VILL-BELPUKUR, P.O. BALARAMPUR, BERHAMPORE, MURSHIDABAD"
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,"Vill-Belpukur, P.O. Balarampur, Berhampore, Murshidabad, West Bengal","West Bengal, VILL-BELPUKUR, P.O. BALARAMPUR, BERHAMPORE, MURSHIDABAD"
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,"Vill-Belpukur, P.O. Balarampur, Berhampore, Murshidabad, West Bengal","VILL-BELPUKUR, P.O. BALAMAMPUR, BERHAMPORE, MURSHIDABAD, West Bengal"
18,Reet Exports (India) Private Limited,reetexportsindia.com,"Vill-Belpukur, P.O. Balarampur, Berhampore, Murshidabad, West Bengal","VILL-BELPUKUR, P.O. BALARAMPUR, BERHAMPORE, MURSHIDABAD, West Bengal"
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,"Vill-Belpukur, P.O. Balarampur, Berhampore, Murshidabad, West Bengal","Vill-belpukur, Murshidabad, WB"

In [17]:
print(sample_pairs.shape)

(34567, 4)

In [18]:
## robust normalization(robust normalized name + core name)
import re
import unicodedata

def normalize_name(name):
    if pd.isna(name):
        return ""

    name = str(name).lower()

    # Normalize accented characters
    name = unicodedata.normalize("NFKD", name)
    name = "".join(
        ch for ch in name
        if not unicodedata.combining(ch)
    )

    # Remove URLs
    name = re.sub(r"https?://\S+|www\.\S+", " ", name)

    # Replace punctuation with spaces
    name = re.sub(r"[^a-z0-9\s]", " ", name)

    # Remove extra spaces
    name = re.sub(r"\s+", " ", name).strip()

    return name

In [19]:
test_names = [
    "FQ Social, Inc",
    "FQ Social, Inc.",
    "FQ Social, Ínc",
    "Arcxylo DBA FQ Social, Inc"
]

for name in test_names:
    print(name, " -> ", normalize_name(name))

FQ Social, Inc  ->  fq social inc
FQ Social, Inc.  ->  fq social inc
FQ Social, Ínc  ->  fq social inc
Arcxylo DBA FQ Social, Inc  ->  arcxylo dba fq social inc

In [20]:
## extracting suffixes
SUFFIXES = [
    "private limited",
    "private ltd",
    "pvt limited",
    "pvt ltd",
    "limited",
    "ltd",
    "corporation",
    "corp",
    "incorporated",
    "inc",
    "company",
    "co",
    "llc",
    "llp"
]


def extract_suffix(name):

    name = normalize_name(name)

    for suffix in sorted(SUFFIXES, key=len, reverse=True):

        if name.endswith(" " + suffix):
            return suffix

    return ""

In [21]:
for name in test_names:
    print(name, " -> ", extract_suffix(name))

FQ Social, Inc  ->  inc
FQ Social, Inc.  ->  inc
FQ Social, Ínc  ->  inc
Arcxylo DBA FQ Social, Inc  ->  inc

In [22]:
## create the core names
def extract_core_name(name):

    name = normalize_name(name)

    suffix = extract_suffix(name)

    if suffix:
        name = name[:-len(suffix)].strip()

    return name

In [23]:
sample_pairs["s1_norm"] = sample_pairs["s1_name"].apply(normalize_name)
sample_pairs["matched_norm"] = sample_pairs["matched_name"].apply(normalize_name)

sample_pairs["s1_suffix"] = sample_pairs["s1_name"].apply(extract_suffix)
sample_pairs["matched_suffix"] = sample_pairs["matched_name"].apply(extract_suffix)

sample_pairs["s1_core"] = sample_pairs["s1_name"].apply(extract_core_name)
sample_pairs["matched_core"] = sample_pairs["matched_name"].apply(extract_core_name)

In [24]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "s1_norm",
        "matched_norm",
        "s1_core",
        "matched_core",
        "s1_suffix",
        "matched_suffix"
    ]
].head(20)

,s1_name,matched_name,s1_norm,matched_norm,s1_core,matched_core,s1_suffix,matched_suffix
0,"FQ Social, Inc","FQ Social, Inc.",fq social inc,fq social inc,fq social,fq social,inc,inc
1,"FQ Social, Inc","FQ Social, #42836",fq social inc,fq social 42836,fq social,fq social 42836,inc,
2,"FQ Social, Inc","FQ Social, Ínc",fq social inc,fq social inc,fq social,fq social,inc,inc
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",fq social inc,arcxylo dba fq social inc,fq social,arcxylo dba fq social,inc,inc
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,innovative consultants,,innovative consultants,,,
5,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,innovative consultants,innovative consultants,,
6,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,innovative consultants,innovative consultants,,
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,hyderabad 500060 kumar private limited,hyderabad 500060 kumar,hyderabad 500060 kumar,hyderabad 500060 kumar,private limited,
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,hyderabad 500060 kumar private limited,hyderabad 500060 kumar private limited,hyderabad 500060 kumar,hyderabad 500060 kumar,private limited,private limited
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",bishop melton and schmidt foods,bishop melton and schmidt foods lp,bishop melton and schmidt foods,bishop melton and schmidt foods lp,,
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",bishop melton and schmidt foods,bishop melton and schmidt foods inc,bishop melton and schmidt foods,bishop melton and schmidt foods,,inc
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods,,
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,golden classic fox llc,golden classic llc partners,golden classic fox,golden classic llc partners,llc,
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,golden classic fox llc,golden classic fox llc,golden classic fox,golden classic fox,llc,llc
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",golden classic fox llc,golden fox llc center,golden classic fox,golden fox llc center,llc,
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,reet exports india private limited,reet exports india private limited,reet exports india,reet exports india,private limited,private limited
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,reet exports india private limited,reet exports india limited services,reet exports india,reet exports india limited services,private limited,
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,reet exports india private limited,reet exports india private limited,reet exports india,reet exports india,private limited,private limited
18,Reet Exports (India) Private Limited,reetexportsindia.com,reet exports india private limited,reetexportsindia com,reet exports india,reetexportsindia com,private limited,
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,reet exports india private limited,reet exports india private limited,reet exports india,reet exports india,private limited,private limited

In [25]:
## get better names

def remove_numbers(name):
    if pd.isna(name):
        return ""
    name = str(name)
    # Remove numbers
    name = re.sub(r'\d+', ' ', name)
    # Remove extra spaces
    name = re.sub(r'\s+', ' ', name).strip()
    return name

def get_name_no_numbers(name):
    name = normalize_name(name)

    # Remove numbers
    name = re.sub(r'\d+', ' ', name)

    # Remove extra spaces
    name = re.sub(r'\s+', ' ', name).strip()

    return name

In [26]:
sample_pairs["s1_no_numbers"] = sample_pairs["s1_name"].apply(get_name_no_numbers)

sample_pairs["matched_no_numbers"] = sample_pairs["matched_name"].apply(get_name_no_numbers)

In [27]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "s1_core",
        "matched_core",
        "s1_no_numbers",
        "matched_no_numbers"
    ]
].head(20)

,s1_name,matched_name,s1_core,matched_core,s1_no_numbers,matched_no_numbers
0,"FQ Social, Inc","FQ Social, Inc.",fq social,fq social,fq social inc,fq social inc
1,"FQ Social, Inc","FQ Social, #42836",fq social,fq social 42836,fq social inc,fq social
2,"FQ Social, Inc","FQ Social, Ínc",fq social,fq social,fq social inc,fq social inc
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",fq social,arcxylo dba fq social,fq social inc,arcxylo dba fq social inc
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,innovative consultants,,innovative consultants,
5,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,innovative consultants,innovative consultants
6,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,innovative consultants,innovative consultants
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,hyderabad 500060 kumar,hyderabad 500060 kumar,hyderabad kumar private limited,hyderabad kumar
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,hyderabad 500060 kumar,hyderabad 500060 kumar,hyderabad kumar private limited,hyderabad kumar private limited
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",bishop melton and schmidt foods,bishop melton and schmidt foods lp,bishop melton and schmidt foods,bishop melton and schmidt foods lp
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods inc
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods,bishop melton and schmidt foods
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,golden classic fox,golden classic llc partners,golden classic fox llc,golden classic llc partners
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,golden classic fox,golden classic fox,golden classic fox llc,golden classic fox llc
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",golden classic fox,golden fox llc center,golden classic fox llc,golden fox llc center
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,reet exports india,reet exports india,reet exports india private limited,reet exports india private limited
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,reet exports india,reet exports india limited services,reet exports india private limited,reet exports india limited services
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,reet exports india,reet exports india,reet exports india private limited,reet exports india private limited
18,Reet Exports (India) Private Limited,reetexportsindia.com,reet exports india,reetexportsindia com,reet exports india private limited,reetexportsindia com
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,reet exports india,reet exports india,reet exports india private limited,reet exports india private limited

In [28]:
def extract_domain_name(name):

    if pd.isna(name):
        return ""

    name = str(name).lower().strip()

    # Remove protocol
    name = re.sub(r'^https?://', '', name)

    # Remove www.
    name = re.sub(r'^www\.', '', name)

    # Remove path
    name = name.split('/')[0]

    # Check whether it looks like a domain
    if '.' in name:
        parts = name.split('.')

        # Remove common domain extensions
        if parts[-1] in ["com", "org", "net", "in", "co", "biz"]:
            return parts[0]

    return ""

In [29]:
print(extract_domain_name("reetexportsindia.com"))

reetexportsindia

In [30]:
sample_pairs["s1_domain"] = sample_pairs["s1_name"].apply(extract_domain_name)

sample_pairs["matched_domain"] = sample_pairs["matched_name"].apply(extract_domain_name)

In [31]:
sample_pairs[
    [
        "s1_name",
     "matched_name",
     "s1_domain",
     "matched_domain"]
    ].head(30)

,s1_name,matched_name,s1_domain,matched_domain
0,"FQ Social, Inc","FQ Social, Inc.",,
1,"FQ Social, Inc","FQ Social, #42836",,
2,"FQ Social, Inc","FQ Social, Ínc",,
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",,
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,,
5,Innovative Consultants,Innovative Consultants,,
6,Innovative Consultants,Innovative Consultants,,
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,,
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,,
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",,
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",,
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",,
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,,
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,,
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",,
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,,
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,,reet exports (india) limited services | www
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,,
18,Reet Exports (India) Private Limited,reetexportsindia.com,,reetexportsindia
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,,
20,Reet Exports (India) Private Limited,Reet (lndia) Exports Private [Limited],,
21,Brightium Lithium LLC,brightium lithium llc,,
22,Brightium Lithium LLC,Brightium (Lithium),,
23,Life Construction Private Limited,लाइफ कंस्ट्रक्शन प्राइवेट लिमिटेड,,
24,Life Construction Private Limited,Shri Life Construction Private,,
25,Anchor Staking Inc,Anchor Stáking Inc,,
26,Anchor Staking Inc,anchor staking inc,,
27,Anchor Staking Inc,ANCHOR STAKIFNG INC,,
28,Anchor Staking Inc,Anchorstaking.Com,,anchorstaking
29,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,,

In [32]:
sample_pairs.columns

Index(['s1_name', 'matched_name', 's1_address', 'matched_address', 's1_norm',
       'matched_norm', 's1_suffix', 'matched_suffix', 's1_core',
       'matched_core', 's1_no_numbers', 'matched_no_numbers', 's1_domain',
       'matched_domain'],
      dtype='object')

In [33]:
def extract_dba_name(name):

    if pd.isna(name):
        return ""

    name = normalize_name(name)

    match = re.search(r'\bdba\b\s+(.*)', name)

    if match:
        return match.group(1).strip()

    return ""

In [34]:
sample_pairs["s1_dba"] = sample_pairs["s1_name"].apply(extract_dba_name)

sample_pairs["matched_dba"] = sample_pairs["matched_name"].apply(extract_dba_name)

In [35]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "s1_dba",
        "matched_dba"
    ]
].head(20)

,s1_name,matched_name,s1_dba,matched_dba
0,"FQ Social, Inc","FQ Social, Inc.",,
1,"FQ Social, Inc","FQ Social, #42836",,
2,"FQ Social, Inc","FQ Social, Ínc",,
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",,fq social inc
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,,
5,Innovative Consultants,Innovative Consultants,,
6,Innovative Consultants,Innovative Consultants,,
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,,
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,,
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",,
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",,
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",,
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,,
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,,
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",,
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,,
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,,
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,,
18,Reet Exports (India) Private Limited,reetexportsindia.com,,
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,,

In [36]:
## Tf-idf vectorization
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 4)
)

all_names = pd.concat([
    sample_pairs["s1_norm"],
    sample_pairs["matched_norm"]
]).fillna("")

vectorizer.fit(all_names)

s1_vec = vectorizer.transform(sample_pairs["s1_norm"])
matched_vec = vectorizer.transform(sample_pairs["matched_norm"])

sample_pairs["name_tfidf_similarity"] = [
    cosine_similarity(s1_vec[i], matched_vec[i])[0][0]
    for i in range(len(sample_pairs))
]

In [37]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "s1_core",
        "matched_core",
        "name_tfidf_similarity"
    ]
].head(50)

,s1_name,matched_name,s1_core,matched_core,name_tfidf_similarity
0,"FQ Social, Inc","FQ Social, Inc.",fq social,fq social,1.000000
1,"FQ Social, Inc","FQ Social, #42836",fq social,fq social 42836,0.555212
2,"FQ Social, Inc","FQ Social, Ínc",fq social,fq social,1.000000
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",fq social,arcxylo dba fq social,0.551120
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,innovative consultants,,0.000000
5,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,1.000000
6,Innovative Consultants,Innovative Consultants,innovative consultants,innovative consultants,1.000000
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,hyderabad 500060 kumar,hyderabad 500060 kumar,0.937303
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,hyderabad 500060 kumar,hyderabad 500060 kumar,1.000000
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",bishop melton and schmidt foods,bishop melton and schmidt foods lp,0.963320
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",bishop melton and schmidt foods,bishop melton and schmidt foods,0.966667
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",bishop melton and schmidt foods,bishop melton and schmidt foods,1.000000
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,golden classic fox,golden classic llc partners,0.598759
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,golden classic fox,golden classic fox,1.000000
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",golden classic fox,golden fox llc center,0.602395
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,reet exports india,reet exports india,1.000000
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,reet exports india,reet exports india limited services,0.779376
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,reet exports india,reet exports india,1.000000
18,Reet Exports (India) Private Limited,reetexportsindia.com,reet exports india,reetexportsindia com,0.435526
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,reet exports india,reet exports india,1.000000
20,Reet Exports (India) Private Limited,Reet (lndia) Exports Private [Limited],reet exports india,reet lndia exports,0.689515
21,Brightium Lithium LLC,brightium lithium llc,brightium lithium,brightium lithium,1.000000
22,Brightium Lithium LLC,Brightium (Lithium),brightium lithium,brightium lithium,0.949420
23,Life Construction Private Limited,लाइफ कंस्ट्रक्शन प्राइवेट लिमिटेड,life construction,,0.000000
24,Life Construction Private Limited,Shri Life Construction Private,life construction,shri life construction private,0.802405
25,Anchor Staking Inc,Anchor Stáking Inc,anchor staking,anchor staking,1.000000
26,Anchor Staking Inc,anchor staking inc,anchor staking,anchor staking,1.000000
27,Anchor Staking Inc,ANCHOR STAKIFNG INC,anchor staking,anchor stakifng,0.688539
28,Anchor Staking Inc,Anchorstaking.Com,anchor staking,anchorstaking com,0.668516
29,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,bharat infra,,0.000000
30,Bharat Infra Private Limited,Bharat Private Limited Center,bharat infra,bharat private limited center,0.599181
31,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,bharat infra,,0.000000
32,Galaxy Projects Private Limited,గెలాక్సీ Projects Private Limited,galaxy projects,projects,0.754234
33,R K Hernandez Sky LLC,R K HERNANDEZ SKY,r k hernandez sky,r k hernandez sky,0.925857
34,R K Hernandez Sky LLC,R K Hernandez Sky L.L.C.,r k hernandez sky,r k hernandez sky l l c,0.906959
35,R K Hernandez Sky LLC,R K Henandz Sky LLC,r k hernandez sky,r k henandz sky,0.641464
36,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,mukta india india,mukta india india,0.946492
37,Mukta India (India) Pvt Ltd,M/s MUKTA ÍNDIA (INDIA) PVT LTD,mukta india india,m s mukta india india,0.907741
38,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,mukta india india,mukta india india,0.946492
39,Mukta India (India) Pvt Ltd,M/s Mukta India (India) Pvt Limited,mukta india india,m s mukta india india,0.861687
40,Mukta India (India) Pvt Ltd,Mukta (India) Pvt Ltd Partners,mukta india india,mukta india pvt ltd partners,0.782388
41,Macro Food LLP,MACRO FOOD LLP,macro food,macro food,1.000000
42,Macro Food LLP,Macro Food LLP,macro food,macro food,1.000000
43,Macro Food LLP,Fayevionovi,macro food,fayevionovi,0.000000
44,Macro Food LLP,Macr0 Food LLP,macro food,macr0 food,0.531141
45,Macro Food LLP,macro food [llp],macro food,macro food,1.000000
46,Cypress,Cypsres,cypress,cypsres,0.255472
47,Cypress,Cypress,cypress,cypress,1.000000
48,Cypress,CYPRESS,cypress,cypress,1.000000
49,Cypress,Cypress,cypress,cypress,1.000000

In [38]:
core_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 4)
)

all_core_names = pd.concat([
    sample_pairs["s1_core"],
    sample_pairs["matched_core"]
]).fillna("")

core_vectorizer.fit(all_core_names)

s1_core_vec = core_vectorizer.transform(
    sample_pairs["s1_core"]
)

matched_core_vec = core_vectorizer.transform(
    sample_pairs["matched_core"]
)

sample_pairs["core_tfidf_similarity"] = [
    cosine_similarity(
        s1_core_vec[i],
        matched_core_vec[i]
    )[0][0]
    for i in range(len(sample_pairs))
]

In [39]:
sample_pairs[
    [
        "s1_name",
        "matched_name",
        "name_tfidf_similarity",
        "core_tfidf_similarity"
    ]
].head(50)

,s1_name,matched_name,name_tfidf_similarity,core_tfidf_similarity
0,"FQ Social, Inc","FQ Social, Inc.",1.000000,1.000000
1,"FQ Social, Inc","FQ Social, #42836",0.555212,0.582102
2,"FQ Social, Inc","FQ Social, Ínc",1.000000,1.000000
3,"FQ Social, Inc","Arcxylo DBA FQ Social, Inc",0.551120,0.509114
4,Innovative Consultants,इनोवेटिव कंसल्टेंट्स,0.000000,0.000000
5,Innovative Consultants,Innovative Consultants,1.000000,1.000000
6,Innovative Consultants,Innovative Consultants,1.000000,1.000000
7,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar,0.937303,1.000000
8,Hyderabad-500060 Kumar Private Limited,Hyderabad-500060 Kumar Private Límited,1.000000,1.000000
9,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods [LP]",0.963320,0.954003
10,"Bishop, Melton and Schmidt Foods","Bishop, Melton and Schmidt Foods Inc",0.966667,1.000000
11,"Bishop, Melton and Schmidt Foods","Bishop, Melton And Schmidt Foods",1.000000,1.000000
12,"Golden Classic Fox, LLC",GOLDEN CLASSIC LLC PARTNERS,0.598759,0.616608
13,"Golden Classic Fox, LLC",Golden Classic Fox LLC,1.000000,1.000000
14,"Golden Classic Fox, LLC","Golden Fox, LLC Center",0.602395,0.405196
15,Reet Exports (India) Private Limited,Reet Exports (India) Private Limited,1.000000,1.000000
16,Reet Exports (India) Private Limited,Reet Exports (India) Limited Services | www.reetexpor.com,0.779376,0.750656
17,Reet Exports (India) Private Limited,Reet Exports(India) Private Limited,1.000000,1.000000
18,Reet Exports (India) Private Limited,reetexportsindia.com,0.435526,0.453085
19,Reet Exports (India) Private Limited,Reet Éxports (India) Private Limited,1.000000,1.000000
20,Reet Exports (India) Private Limited,Reet (lndia) Exports Private [Limited],0.689515,0.582929
21,Brightium Lithium LLC,brightium lithium llc,1.000000,1.000000
22,Brightium Lithium LLC,Brightium (Lithium),0.949420,1.000000
23,Life Construction Private Limited,लाइफ कंस्ट्रक्शन प्राइवेट लिमिटेड,0.000000,0.000000
24,Life Construction Private Limited,Shri Life Construction Private,0.802405,0.712753
25,Anchor Staking Inc,Anchor Stáking Inc,1.000000,1.000000
26,Anchor Staking Inc,anchor staking inc,1.000000,1.000000
27,Anchor Staking Inc,ANCHOR STAKIFNG INC,0.688539,0.676334
28,Anchor Staking Inc,Anchorstaking.Com,0.668516,0.680230
29,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,0.000000,0.000000
30,Bharat Infra Private Limited,Bharat Private Limited Center,0.599181,0.363722
31,Bharat Infra Private Limited,भारत इंफ्रा प्राइवेट लिमिटेड,0.000000,0.000000
32,Galaxy Projects Private Limited,గెలాక్సీ Projects Private Limited,0.754234,0.636745
33,R K Hernandez Sky LLC,R K HERNANDEZ SKY,0.925857,1.000000
34,R K Hernandez Sky LLC,R K Hernandez Sky L.L.C.,0.906959,0.853348
35,R K Hernandez Sky LLC,R K Henandz Sky LLC,0.641464,0.584733
36,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,0.946492,1.000000
37,Mukta India (India) Pvt Ltd,M/s MUKTA ÍNDIA (INDIA) PVT LTD,0.907741,0.889540
38,Mukta India (India) Pvt Ltd,Mukta India (India) Pvt Limited,0.946492,1.000000
39,Mukta India (India) Pvt Ltd,M/s Mukta India (India) Pvt Limited,0.861687,0.889540
40,Mukta India (India) Pvt Ltd,Mukta (India) Pvt Ltd Partners,0.782388,0.613429
41,Macro Food LLP,MACRO FOOD LLP,1.000000,1.000000
42,Macro Food LLP,Macro Food LLP,1.000000,1.000000
43,Macro Food LLP,Fayevionovi,0.000000,0.000000
44,Macro Food LLP,Macr0 Food LLP,0.531141,0.407247
45,Macro Food LLP,macro food [llp],1.000000,1.000000
46,Cypress,Cypsres,0.255472,0.254509
47,Cypress,Cypress,1.000000,1.000000
48,Cypress,CYPRESS,1.000000,1.000000
49,Cypress,Cypress,1.000000,1.000000